### ISSUE TITLE
Using Algolia with Twitter Typeahead 0.11.1

### ISSUE THREAD

**Issue by rhokstar** [algolia/algoliasearch-client-js#105]
I want to use the newest version because of the new custom events it offers. When trying to use the new version, the results no longer show. I'm still seeing queries being made however.

**Comment by redox** [comment]
Indeed, it seems they changed the way their callback is working. Here is the new code of Bloodhound's `ttAdapter`: https://github.com/twitter/typeahead.js/blob/master/dist/bloodhound.js#L825-L834

We can probably handle the backward compatibility based on the 2nd parameter (now a `sync` boolean and before a `cb` function).
