### ISSUE TITLE
CommonJS-compliant angular build

### ISSUE THREAD

**Issue by redox** [algolia/algoliasearch-client-js#109]
I want to do something like:
```
'use strict';

var angular = require('angular');
require('angular-sanitize');
require('angular-algoliasearch');

angular.module('myApp', ['ngSanitize', 'algoliasearch'])
  .controller('SearchCtrl', ['$scope', '$sce', 'algolia', function($scope, $sce, algolia) {
  }]);
```

**Comment by vvo** [comment]
I do not know how to do commonJS compatible angularjs modules. AH!

I think if it's commonJS compatible then for-sure you will not do `require('angular-algoliasearch')` but rather `var algoliasearchService = require('angular-algoliasearch')`.

Ill have a look at how they do this by looking at well known modules

**Comment by vvo** [comment]
Did you try `require('algoliasearch/src/browser/builds/algoliasearch.angular')` as a first workaround?

**Comment by vvo** [comment]
What you are trying to do is not commonJS, it's just loading using require, it will attach algoliasearch service to the globally available angularjs if found.

**Comment by redox** [comment]
Ah interesting :) Let me try!
