### ISSUE TITLE
Reserved keyword used for an attribute

### ISSUE THREAD

**Issue by Nagriar** [algolia/algoliasearch-client-js#113]
When I try to minify the javascript code with Yahoo compressor, I have an exception here for example:
https://github.com/algolia/algoliasearch-client-js/blob/master/dist/algoliasearch.angular.js#L1168

The error message is: missing name after . operator

**Comment by vvo** [comment]
Sounds like a problem of `ms` module and yui https://github.com/rauchg/ms.js/pull/40.

Did we have a user experiencing this?

**Comment by Nagriar** [comment]
Yes, the issue was repported by a user. He had the issue after the release of the v3.

**Comment by vvo** [comment]
Ok a release will be done tomorrow with the fix I have done @Nagriar, do we have to warn someone?
