### ISSUE TITLE
Ability to set secured query parameters more easily

### ISSUE THREAD

**Issue by redox** [algolia/algoliasearch-client-js#116]
Right now we need to do:
```
client.setExtraHeader('X-Algolia-QueryParameters', 'numericFilters=user_id%3d42');
```

I would like to do:
```
client.setSecuredQueryParameters({ numericFilters: "user_id=42" });
```

**Comment by Nagriar** [comment]
Be carefully, the order is important: 
{ numericFilters: "user_id=42", hitsPerPage: 1 } can be encoded in "numericFilters=user_id%3d42&hitsPerPage=1" or "hitsPerPage=1&numericFilters=user_id%3d42" but only one of them is the valid key for the X-Algolia-QueryParameters signature.

**Comment by redox** [comment]
Yes indeed, that's super complex actually :/

**Comment by Nagriar** [comment]
Even if we sort the keys: { numericFilters: ["user_id=42", "user_id=43"]} can be encoded in json or string format

**Comment by vvo** [comment]
Not sure this is a real world issue since we never had a client having it?

Otherwise, we first need to make sure that every API client encodes to JSON in alphabetical order when generating the api key.

Then on the backend side, at query time, reorder the provided secure keys and do the match.

I think ES6 standardized the key order.

**Comment by Nagriar** [comment]
If a user set { numericFilters: "(user_id=42,user_id=43)"}, we will need to parse it and convert it that case

**Comment by vvo** [comment]
We should maybe leave this edge case on the user side.

**Comment by Nagriar** [comment]
What will be the order for: ["a", "b", [ "c", "d"]]:  ["a", "b", [ "c", "d"]] or  [[ "c", "d"], "a", "b"] ?

**Comment by vvo** [comment]
Do not get the question.

Order within a JSON object stringified should really be the same for every engine (we could first do the testing ourselves before trying to fix it).

Order for a user string value inside an object: `{numericFilters: "(user_id=42,user_id=43)"}` is unchanged, but could be different from the moment the client generated the key. For this case I think it's an edge case.

**Comment by vvo** [comment]
> What will be the order for: ["a", "b", [ "c", "d"]]: ["a", "b", [ "c", "d"]] or [[ "c", "d"], "a", "b"] ?

When using JSON.stringify (any engine), order should the same since arrays are ordered, whereas maps are not (but ordered internally, that's the possible bug)

**Comment by vvo** [comment]
This seems outdated with the new secured api key we are introducing

**Comment by acorncom** [comment]
@vvo Any link to the new secured api key docs?

**Comment by vvo** [comment]
@acorncom I am currently implementing it, then we will document its usage, I will update this issue accordingly.
