### ISSUE TITLE
jsonp fallback triggered with Angular + Basic Auth

### ISSUE THREAD

**Issue by pixelastic** [algolia/algoliasearch-client-js#124]
It seems that when using the Angular build behind a Basic Auth website, we fallback to jsonp. This is because in order to make Angular queries correctly work behind a Basic Auth, one have to add the `withCredentials: true` to its Angular config.

And we do not turn it off when requesting our backend, which results in a failed request and the triggering of the jsonp fallback. We should force `withCredentials: false` when requesting our backend.

cc @vvo We talked about it earlier, and were supposed to fix it together in peer programming but never got the chance

**Comment by vvo** [comment]
this was fixed and released
