### ISSUE TITLE
Setup a search-only "lite" version of the JS client

### ISSUE THREAD

**Issue by acorncom** [algolia/algoliasearch-client-js#127]
I'm working on a JS single-page app where we're going to be embedding many of our vendor files.  I'd prefer to not embed the entire REST client, as we'll be using search-only keys in a read-only context.  Would there be any way we could subscribe to a JS "lite" version of the client that you guys support to keep our bundle size down?

**Comment by vvo** [comment]
Hi @acorncom, that's feasible. It depends on the size reduction you are looking at.

Do you know how much size you would want to shrink?  

We have ways to reduce the filesize to smg like 8kb for a search only client

**Comment by acorncom** [comment]
@vvs 8kb seems quite reasonable. Just would rather not be including code to handle creating indexes when I *know* I will never use it on the client :-)

**Comment by acorncom** [comment]
@vvs the reduction in size might also help with the resistance you guys seem to be getting from the Bootstrap folks ... :-)

**Comment by vvo** [comment]
Yes but we are a bit relunctant to build, document and maintain an 8kb js client.

Is 12kb filesize reduction on a 1,5mb website worth it?

Will it make a difference on the page load time? On a low connection network yes, but not if your webpage weights 1.5mb because people will left the wenaite before we start downloading 8kb client.

Do you see what I mean? Can you provide us some numbers (current webpage size) or maybe your website url?

I am still ok for doing the light version, only want to really understand the use case

**Comment by vvo** [comment]
> Just would rather not be including code to handle creating indexes when I *know* I will never use it on the client :-)

Depending on the other libraries you are using (only algolia?) there is a good chance you have a lot of unused code in your webpage. Not just algolia.

**Comment by acorncom** [comment]
> Depending on the other libraries you are using (only algolia?) there is a good chance you have a lot of unused code in your webpage. Not just algolia.

Agreed.

> Yes but we are a bit relunctant to build, document and maintain an 8kb js client.

Understood on that.  What I had envisioned when looking at your code was in essence a trimmed down "search-only" parent class with the main library inheriting from it.  But understood about the reluctance to take on the long-term maintenance :-)

> Is 12kb filesize reduction on a 1,5mb website worth it?

For you to make something specifically for me wouldn't make sense, I'd agree (and because I'm using an Ember app, the payload does indeed get quite large).  I'd wondered if there would be a desire / demand for it from other folks (where I might be the first to voice the thought, but not be the primary target audience).

That make sense?  Happy to have you choose either way.

**Comment by vvo** [comment]
> Understood on that. What I had envisioned when looking at your code was in essence a trimmed down "search-only" parent class with the main library inheriting from it

We may be able to do so yes and provide the library users a search only requireable file (and build).

This is a good idea but not top priority.

If you wanna help us: GO!
It would be great, the codebase should be straightforward.

I am available for any question regarding the code base and organisation of the future build.

**Comment by acorncom** [comment]
> This is a good idea but not top priority.

Understood on it not being top priority.  Re: helping on it, I may have time, but don't plan on my doing it :-)

**Comment by vvo** [comment]
As we are using lodash and sharing it amongst our projects I must say that we will maybe never do this unless we drop lodash at some point.

You could always shim the necessary lodash requires with your own utilities, that would work if you really need light size
