### ISSUE TITLE
Potential uncaught exception due to agentkeepalive 

### ISSUE THREAD

**Issue by dg3feiko** [algolia/algoliasearch-client-js#128]
we encountered crashes from algoliasearch client js

part of stack trace is here
```
Error: getaddrinfo ENOTFOUND at errnoException (dns.js:37:11) 
.....

 at ClientRequest.onSocket (http.js:1731:11) 
at HttpsAgent.Agent.addRequest (/..../node_modules/algoliasearch/node_modules/agentkeepalive/lib/_http_agent.js:192:9) at new ClientRequest (http.js:1417:16)

....

```

we think that it is related to some http request socket handling.
so we found
https://github.com/node-modules/agentkeepalive/commit/24afa4a84aefb1d1639b5ea4610539d06ef396c2

it seems that our crashes were very possible related to `agentkeepalive`
please check it and verify, if the patch helps, please apply to as soon as possible.

**Comment by redox** [comment]
Hi @dg3feiko,

thank for reaching us about that. The DNS issues were related to a DNS outage we get (https://status.algolia.com/) but catching that exception is definitely something we need to work on. I'll let @vvo work on it!

**Comment by vvo** [comment]
Hi @dg3feiko,

Can you provide me some more information:
- the nodejs version you are using
- confirm the algoliasearch module version you are using
- how are you initializing the algoliasearch code? So that I can see what are the options you are using

thanks

**Comment by vvo** [comment]
Hi @dg3feiko I was not able to reproduce this problem with your provided setup:
- nodejs 0.10.38
- algoliasearch@3.7.6
- newrelic@1.18.4 // maybe not relevant, still I wanted to be in the same conditions

I am using the callback interface of algoliasearch library.

Here is a simple test file I tried:

```js
require('newrelic')

// node examples/node.js
var algoliasearch = require('../');
var client = algoliasearch('notrelevant', 'fakekey', {
  hosts: {
    read: ['dsadsadsada.dsadsadsadsadwdwdwdwsssdwdwdwdwd.com'], // force algolia hosts to something that will not resolve
    write: []
  }
});
var index = client.initIndex('contacts');

index.search('something', function(err, results) {
  console.log('catched');
  client.destroy();
});
```

Can you try this code in your project and see how it goes? thanks

**Comment by vvo** [comment]
@dg3feiko Ok, I will update agentkeepalive and release a new version.

I think this can happen when you made successful request to Algolia and then something goes wrong with one of our server. Then agentkeepalive crashe(d)s.

Thanks for reporting, I am going to make a release today.

**Comment by vvo** [comment]
@dg3feiko Can you please try the provided test code (report here) and then update to 3.7.7 which I just released (with updated agentkeepalive).

Thanks.

**Comment by nitriques** [comment]
I am having this problem right now. I get

Error! getaddrinfo ENOTFOUND gbc-2.algolianet.com gbc-2.algolianet.com:443

Whenever I try to call your API. I do not have this problem with the same code on other APPS. Can you help ?

**Comment by nitriques** [comment]
So the problem is that the APP id was invalid.

Maybe consider adding a check on that ?

**Comment by maxiloc** [comment]
The main issue is, we don't really have a way to differentiate a network issue from an invalid app_id but indeed maybe we could add in the error message that is could be a bad APP_ID or network issue

**Comment by nitriques** [comment]
Right, that's hard to test.

Could you issue a DNS request manually ? If you get a NOTEXISTENT response, that could prevent trying any HTTPS request... That's the first thing on top of my head.

Thanks!

**Comment by vvo** [comment]
Hi @nitriques indeed we do not do such checks today about the validity of the APPID given the low number of times this can happen. We might add that check in the future if more people are concerned. Thanks
