### ISSUE TITLE
Angular client headers

### ISSUE THREAD

**Issue by ajarti** [algolia/algoliasearch-client-js#135]
Hi guys,

I use your Angular client along with Laravel and have to globally set the X-CSRF-Token for Laravel ajax for POSTs to work.  I am getting an issue with your service not liking the extra headers

I get the error:
 >  Request header field X-CSRF-Token is not allowed by Access-Control-Allow-Headers.

I set the header globally in the app config as I have loads of ajax posts and it's not practical to set it manually every time:
```javascript
 $httpProvider.defaults.headers.common = {
    'X-Requested-With': 'XMLHttpRequest',
    'X-CSRF-Token': $('meta[name="_token"]').attr('content')
};
```
I have tried overriding it using:
```javascript
client.setExtraHeader('X-CSRF-Token', null);
```

That has no effect and I cannot see any methods in the client to remove headers.

Any suggestions?  (Thanks in advance!)

**Comment by asurak** [comment]
I confirm that we do not announce X-CSRF-Token header support. Any ideas around it @vvo ?

**Comment by ajarti** [comment]
Maybe flush existing header in _computeRequestHeaders: line 906 of AlgoliaSearch.js ?

**Comment by vvo** [comment]
Hey to both of you. I will force or clean headers in the angular request build implementation on monday.

If you already have a solution @ajarti feel free to contribute, that's easy!

**Comment by ajarti** [comment]
Hi guys,

I have experimented a bit and in Angular 1.4 you can clear common headers by setting them undefined in the $http request (see: 'Setting HTTP Headers' on https://docs.angularjs.org/api/ng/service/$http)
I wrote a little code to generate the clearing: 

```javascript
var commonHeadersToClear = {};
angular.forEach($http.defaults.headers.common, function(value,key){
    commonHeadersToClear[key] = undefined;
});
```
and then pass then to the 3rd param of the http request and this works fine in normal $http requests. 

I tried to use the js client setExtraHeader method to set them to undefined, but that failed to clear them as it looks like the headers are already flushed but the header is still included in the querystring? It looks like the inlineHeaders function in the client gets to them and just converts the undefined to empty, but still includes the header in the querystring .... and boom!

That is of course if I am reading it correctly :)

Does that help?

**Comment by vvo** [comment]
Yes thanks a lot for this investigation!

**Comment by ajarti** [comment]
Only a pleasure @vvo :) I have a deadline for Monday that I am probably not going to make, so can't allocate any additional time this weekend unfortunately.  I am using Algolia in it so will just manually add the X-CSRF-Token and X-Requested-With to my Laravel API calls for the time being.

Thanks again for looking at this, much appreciated.
