### ISSUE TITLE
Facet values order not honored 

### ISSUE THREAD

**Issue by smallcrew** [algolia/algoliasearch-client-js#136]
JS lib version = 3.7.5

Just to let you know that we are facing an issue with facet value ordering. JS api is changing the order coming from the server.

Response from algolia server
```javascript
{
  "hits": [],
  "nbHits": 37,
  "page": 0,
  "nbPages": 0,
  "hitsPerPage": 0,
  "processingTimeMS": 1,
  "facets": {
    "city": {
      "Paris": 14,
      "Casablanca": 3,
      "12": 1,
      "Boulogne Billancourt": 1,
      "Fontenay Aux Roses": 1,
      "Pontault Combault": 1,
      "Viry Chatillon": 1
    }
  },
  "facets_stats": {
    "city": {
      "min": 12,
      "max": 12,
      "avg": 12
    }
  },
  "exhaustiveFacetsCount": true,
  "query": "",
  "params": "query=&facets=city&hitsPerPage=0&exhaustive=false"
}
```

After JSON.parse in node.js line 166

```javascript
{ hits: [],
  nbHits: 37,
  page: 0,
  nbPages: 0,
  hitsPerPage: 0,
  processingTimeMS: 1,
  facets:
  { city:
  { '12': 1,
    Paris: 14,
    Casablanca: 3,
    'Boulogne Billancourt': 1,
    'Fontenay Aux Roses': 1,
    'Pontault Combault': 1,
    'Viry Chatillon': 1 } },
  facets_stats: { city: { min: 12, max: 12, avg: 12 } },
  exhaustiveFacetsCount: true,
  query: '',
  params: 'query=&facets=city&hitsPerPage=0&exhaustive=false' }

```

Do you plan to return facets in an array like this :
```javascript
{
  "hits": [],
  "nbHits": 37,
  "page": 0,
  "nbPages": 0,
  "hitsPerPage": 0,
  "processingTimeMS": 1,
  "facets": {
    "city": [
      {"Paris": 14},
      {"Casablanca": 3},
      {"12": 1},
      {"Boulogne Billancourt": 1},
      {"Fontenay Aux Roses": 1},
      {"Pontault Combault": 1},
      {"Viry Chatillon": 1}
    ]
  },
  "facets_stats": {
    "city": {
      "min": 12,
      "max": 12,
      "avg": 12
    }
  },
  "exhaustiveFacetsCount": true,
  "query": "",
  "params": "query=&facets=city&hitsPerPage=0&exhaustive=false"
}
```
Or use an another JSON javascript implementation that could keep values order ?

We know that we could sort facets by our self using your helpers but even if it's not a big deal we are doing the same sort order work twice

By the way, is it possible to prevent facets_stats ? there is one "string" number in our column city and it's seems that since its insertion column became numeric

**Comment by vvo** [comment]
Hi @smallcrew, yes unfortunately since we are using a map for `facets` from the API server, the ordering of maps is not something you can rely on.

That's a first issue and returning from the API server an array would be a good idea but it would break every website using algolia since now, cc @redox.

> We know that we could sort facets by our self using your helpers but even if it's not a big deal we are doing the same sort order work twice

What I would recommend is using the https://github.com/algolia/algoliasearch-helper-js we have a new way to do what you want:

```js
helper.on('result', function(result) {
  // Get the facet values for the attribute age
  result.getFacetValues('age', {sortBy: ['count:asc']});
  // It will be ordered by number of occurence (lower number => higher position)
  // Elements that can be sorted : count, name, isRefined
  // Type of sort : 'asc' for ascending order, 'desc' for descending order
});
```

See the documentation https://github.com/algolia/algoliasearch-helper-js/tree/1a685b4e06713a78ff27444c5886dae3fa126dfa#get-the-values-of-a-facet-with-a-custom-sort

> By the way, is it possible to prevent facets_stats ? there is one "string" number in our column city and it's seems that since its insertion column became numeric

It's a little trick used in faceting that is triggering this but you can safely ignore `facets_stats` it if that's ok with you.

Let me know what you think.

**Comment by smallcrew** [comment]
@vvo Well i would prefer to not use the helper, but if there is no other choice. Thanks
