### ISSUE TITLE
Provide a constructor for a writable stream to batch import data

### ISSUE THREAD

**Issue by bobylito** [algolia/algoliasearch-client-js#147]
The index could have a method to create a writable stream that could be piped in order to do a batch push to Algolia. The result could be something like : 

```js
var algoliaStream = algoliasearch(appId, key).initIndex(myIndex).getSaveBatchStream();
fs.createReadStream('data.json')
  .pipe(JSONStream.parse('*'))
  .pipe(es.map(addObjectId))
  .pipe(new batch({size: 5000}))
  .pipe(algoliaStream);
```

**Comment by vvo** [comment]
I am sorry I am not sure I get the question from the title only. Can you precise your need (use case) and solution proposal when you have time? Thx

**Comment by bobylito** [comment]
Updated the description

**Comment by vvo** [comment]
`getSaveBatchStream`: we are doing addObjects so save may not be the best name here?

Maybe createWritableAddObjectsStream? (long :D)

**Comment by vvo** [comment]
I know that the nodejs core API already have something like `createWriteStream` so mapping to the same name may be a good idea.

https://nodejs.org/api/fs.html#fs_fs_createwritestream_path_options

**Comment by vvo** [comment]
@bobylito Will you submit a PR for this or should it be a module?

**Comment by vvo** [comment]
Closing for now
