### ISSUE TITLE
Inconsistent behavior of `browse` with "empty query"

### ISSUE THREAD

**Issue by pixelastic** [algolia/algoliasearch-client-js#149]
I just tried to use the `browse` method and I'm having inconsistent and unexpected behavior (and the doc is not really clear on how to use it).

```javascript
index.browse(null, function(err, content) {
  // content.cursor: AAABlwc=
  // content.params: (empty)
});
index.browse(undefined, function(err, content) {
  // Never called
});
index.browse('', function(err, content) {
  // content.cursor: AAZxdWVyeT0Blwc=
  // content.params: query=
});
index.browse('foo', function(err, content) {
  // content.cursor: AAlxdWVyeT1mb28Bkw0=
  // content.params: query=foo
});
```

What is even more weird is that if I had a second argument of `{ hitsPerPage: 10 }`, this time the call with `undefined` actually gets called, with a cursor.

So what is the correct way to do a `browse` call for an empty query (to get all the results). Should we use an empty string, `undefined` or `null`?

**Comment by vvo** [comment]
I you want to browse the whole index you can just use `browseAll` (https://github.com/algolia/algoliasearch-client-js#backup--retrieve-of-all-index-content).

Or use `browse(function() {})` and manually call `browseFrom`

I do not know why browse(undefined) would not do anything, maybe you can debug it.

**Comment by pixelastic** [comment]
I don't really understand when one should use `browse` instead of `browseAll`, actually.

**Comment by redox** [comment]
> I don't really understand when one should use browse instead of browseAll, actually.

`browseAll` is for whole index export. `browseFrom` is to handle pagination after the 1000-nth hit.

**Comment by vvo** [comment]
> I don't really understand when one should use browse instead of browseAll, actually.

Isn't the readme enough on this subject? https://github.com/algolia/algoliasearch-client-js#backup--retrieve-of-all-index-content If not, we can update it.

**Comment by pixelastic** [comment]
I had a customer not understanding the difference between `browse` and `browseAll`, so I wanted to update the doc to make it clearer. Turns out that I did not realy understood the documentation either.

> browseAll is to export the whole index. browseFrom is to handle pagination after the 1000-nth hit.

So how should I proceed if I want to access the nth page then? Should I do a browse with a specific `page` in params, retrieve the cursor then do a `browseFrom`?

**Comment by vvo** [comment]
> So how should I proceed if I want to access the nth page then?

If accessing it is not too slow you can just use browse and specify the page. The browse with a cursor is only good if accessing  page 90000 is verrrry slow. Then you can use the cursor based approach, but this one works if you have a reference to the previous cursor (thus, in a website, storing it in the url..)

**Comment by vvo** [comment]
This also mean that the SEO url should contain the cursor.

**Comment by vvo** [comment]
Can we close this @pixelastic?

**Comment by pixelastic** [comment]
Not yet, I haven't had time to fix the issue with `undefined`, and I'm in the process of updating the documentation

**Comment by vvo** [comment]
@pixelastic Can we close this?

**Comment by pixelastic** [comment]
Yes, we can close it.

I updated the doc in https://github.com/algolia/algoliasearch-client-readme-generator/pull/11, but I feel like it still miss some real-world browse + cursor examples. The only we have only grab the cursor, but don't do anything with it.
