### ISSUE TITLE
Implement new secured api key

### ISSUE THREAD

**Issue by Nagriar** [algolia/algoliasearch-client-js#150]
To ease the usage of the secured api key, we introduced a new format. Now the api key is a base64 of the secured api key plus the queryParameters used to generate it. You don't need anymore to set the header when you use a secured api key.

    securedKey = hmac(apiKey, urlEncodedQueryParameters)
    newSecuredKey = base64Encode(securedKey + urlEncodedQueryParameters)

It's also possible to convert the previous tagFilters to this new format:

    queryParameters = ._getSearchParams({'tagFilters': tagFilters})

**Comment by vvo** [comment]
Hi @Nagriar, I fail to easily see what we need to change. Can you point to the methods we need to update?

**Comment by vvo** [comment]
> queryParameters = ._getSearchParams({'tagFilters': tagFilters})

Not sure I need to implement this in JS? What's the usecase?

**Comment by Nagriar** [comment]
For this method, https://github.com/algolia/algoliasearch-client-js/blob/75c3ad4a34933edfd187542c58bff7810db2cd97/src/server/builds/node.js#L254-L272
The generated api key is now a base64 string of the secured api key and the query parameters.

We need to update the old way to generate a secured api key with the tagFilters to convert it to a secured api key generated with a query parameters to be able to use the new format.

**Comment by vvo** [comment]
Thanks will implement this soon!
