### ISSUE TITLE
misleading docs

### ISSUE THREAD

**Issue by the1mills** [algolia/algoliasearch-client-js#151]
The docs are a little misleading - the first half make it seem like this lib only allows you to search Algoila indices, but in fact I believe this lib allows you to push data to Algolia as well.

Can you make it a little more clear up front what this library is for or what the limitations are of the lib?

thanks

**Comment by vvo** [comment]
Hi, thanks for opening this issue.

Do you have any insight on how we could make it clearer? That would help. Thanks

**Comment by the1mills** [comment]
I think changing this:

```
The JavaScript client lets you use the Algolia Search API on the frontend (browsers) or on the backend (Node.js) with the same API.
```

into this

```
The JavaScript client lets you use the Algolia Search API on the frontend (browsers) or on the backend (Node.js) with the same API.  Using your Algolia admin API keys, you can use this module to make any type of query to your Algolia deployment.
```

something like that, because with "Algolia Search" in the name instead of just Algolia, it makes it seem that this module is a read-only client.

**Comment by vvo** [comment]
So I propose:

> The JavaScript client lets you use the [Algolia Search API](https://www.algolia.com/doc/rest_api) on the frontend (browsers) or on the backend (Node.js) with the same API.
>
> The backend (Node.js) API can be used to index your data using your Algolia admin API keys.

Is that ok?

**Comment by vvo** [comment]
Was fixed

**Comment by the1mills** [comment]
thx
