### ISSUE TITLE
support - ordering results or index itself by fewer terms

### ISSUE THREAD

**Issue by ORESoftware** [algolia/algoliasearch-client-js#155]
if we had objects like so in an Algolia index:

```javascript
[{
 name: 'lazy fox jumps over'
},
{
name: 'lazy fox jumps'
},
{
name: 'lazy fox'
}]
```

how can we prioritize short results instead of longer results? This is with the assumption that "higher level concepts" usually are shorter - one or two words. Put another way, we want 'lazy fox' to be at the top of the results and 'lazy fox jumps over' to be at the bottom, because it has more words.

is this possible with Algolia?

**Comment by pixelastic** [comment]
Hello,

What I would do is add a new attribute to your records (`word_count`), that you will populate with the number of words in the `namer, and then do your custom ranking based on this value.

## Dashboard config example
![image](https://cloud.githubusercontent.com/assets/283419/10726327/452ef778-7bd2-11e5-8856-05aa4750c184.png)

## Results example
![image](https://cloud.githubusercontent.com/assets/283419/10726319/3e4f4f7a-7bd2-11e5-92a4-eb000d73fc9e.png)

Does it answer your question?

**Comment by ORESoftware** [comment]
sure, that might work, if there is a better/easier way, please let us know, thanks!

**Comment by vvo** [comment]
> if there is a better/easier way, please let us know, thanks!

Currently there is not, basically if you want to modify the ranking order based on your dataset, the simplest way is always to precompute the relevant data (here being number of words in an attribute) and then add the attribute to custom ranking.

Thanks!
