### ISSUE TITLE
Using algoliasearch in React Native

### ISSUE THREAD

**Issue by votive** [algolia/algoliasearch-client-js#162]
I've added the algoliasearch npm package in my React Native project and initialise it correctly but at runtime the application errors with this message: Requiring unknown module "crypto". This is presumably because crypto is not available in the context of a React Native application. How should I call the Algolia API in a React Native application?

**Comment by redox** [comment]
@bobylito started to work on that in https://github.com/algolia/algoliasearch-client-js/tree/feature/reactnativebuild -> any update on this?

**Comment by bobylito** [comment]
I guess it's time to merge that new build :) Next release will have that :)

**Comment by redox** [comment]
> I guess it's time to merge that new build :) Next release will have that :)

And you didn't have any issue with the `crypto` module, right?

**Comment by bobylito** [comment]
Yes I did, that's one of the purpose of this specific build :)

**Comment by bobylito** [comment]
PR is in progress :) #163

**Comment by vvo** [comment]
Was released as 3.9.2, can you try @votive?

**Comment by votive** [comment]
@vvo if I include the library like this:

    let algoliaSearch = require('algoliasearch');

I get the same crypto error. If I include this file:

    let algoliaSearch = require('algoliasearch/src/reactnative/builds/algoliasearch.reactnative');

then it works fine :) Is that the correct include?

**Comment by vvo** [comment]
You should be able to do algolia/reactnative

**Comment by votive** [comment]
Thanks that's working perfectly!
