### ISSUE TITLE
querystring dependency not included for react-native

### ISSUE THREAD

**Issue by deanmcpherson** [algolia/algoliasearch-client-js#167]
Hey there,

Installed this client for react-native and got a module not found error that querystring couldn't be found. I npm installed it and all worked as expected, you might need to add querystring as a dependency in your package.json.

**Comment by bobylito** [comment]
Thanks @deanmcpherson. It seems that we actually need to include `events` as well. :) Fixing that right now :)

**Comment by vvo** [comment]
Was released as 3.9.3 @deanmcpherson
