### ISSUE TITLE
Using Algoliasearch Client JS Angular Module with RequireJS in a Rails Application

### ISSUE THREAD

**Issue by aslam** [algolia/algoliasearch-client-js#168]
Hello,

Even though the [Wiki](https://github.com/algolia/algoliasearch-client-js/wiki/Migration-guide-from-2.x.x-to-3.x.x#umd-compatibility) says it supports all major module loaders, I am unable to figure this one out. Googling is not yielding any helpful results. 
I am trying to use this client (Angular build) in our existing Rails application where in we use RequireJS for AMD support with pre-compilation.  I am using [requirejs-rails gem[(https://github.com/jwhitley/requirejs-rails) and maintaining a requirejs.yml to maintain paths config:

![image](https://cloud.githubusercontent.com/assets/95872/11361269/6064bb44-92b2-11e5-8681-d3b6fabf623a.png)
and the files under ```/vendor``` directory:
![image](https://cloud.githubusercontent.com/assets/95872/11361223/eaaedf9c-92b1-11e5-97f7-26a54da7033f.png)

I am adding this to the angular module:
```
var app = angular.module('events', [
        'app.controllers',
        'app.directives',
        'app.filters',
        'app.factories',
        'app.services',
        'ngCookies',
        'algoliasearch'
    ]);
```
it is unable to find this module and looking at a wrong place:

![request](https://cloud.githubusercontent.com/assets/95872/11361942/ac7328aa-92b6-11e5-9cb0-19f535561b58.jpg)

This setup works in my local environment, but compiling the assets gives problems. Any pointers to resolve this issue is appreciated.

**Comment by vvo** [comment]
Hi @aslam do you think you could give us a simple repository where we could experiment based on the same setup you have?

So that we could help you further solve this issue.

Basically a simple setup reproducing your issue (with maybe less dependencies).

Let me know

**Comment by aslam** [comment]
@vvo thanks for the response. This would be a difficult because the issue happens only on pre-compilation. But, let me give this a shot in a new project and try and re-produce the issue. Thanks.

**Comment by aslam** [comment]
@vvo came up with a sample application whose setup is similar to like of the original application: https://github.com/aslam/test_algolia_angular_require. Hope this helps.

**Comment by vvo** [comment]
Thanks I am going to test this now

**Comment by vvo** [comment]
@aslam You are using algoliasearc 2.5.1 it seems, can you try this file instead: https://cdn.jsdelivr.net/algoliasearch/3.9.2/algoliasearch.angular.js

**Comment by aslam** [comment]
@vvo I am using the latest version itself: https://github.com/aslam/test_algolia_angular_require/blob/master/vendor/assets/javascripts/v3/angular/modules/angular-algoliasearch.js. Not sure where did you determine that I am using v2.5.1?

**Comment by vvo** [comment]
Ah yes sorry, foud it here: https://github.com/aslam/test_algolia_angular_require/blob/master/vendor/assets/javascripts/algoliasearch.js

**Comment by vvo** [comment]
So the issue is that you are trying to load "angular-algoliaSearch.js" whereas the filename is "angular-algoliasearch.js". 

Also I was not able to run your provided project, what command do I need to do so that I can reproduce the 404 request you had?

**Comment by redox** [comment]
> So the issue is that you are trying to load "angular-algoliaSearch.js" whereas the filename is "angular-algoliasearch.js".

Oh :) I guess you're on a Mac (case insensitive) while developing locally and on linux (case sensitive) while precompiling the assets :) ?

**Comment by aslam** [comment]
@vvo I don't think this is an issue. Please see: https://github.com/aslam/test_algolia_angular_require/blob/master/config/requirejs.yml#L106. As mentioned, I am using requirejs-rails gem and maintaining requirejs.yml file to map paths with the modules I am using. So, the path ```"v3/angular/modules/angular-algoliasearch"``` is mapped to ```angular.algoliaSearch``` which I am trying to use.

**Comment by vvo** [comment]
@aslam The error you are getting in the console, this:

![image](https://cloud.githubusercontent.com/assets/123822/11392336/5671fca8-9359-11e5-8a77-7a5c4e2acfe3.png)

is saying that you are trying to load algoliaSearch.js while it does not exists in your environment.

Can you try change all places where you are using "algoliaSearch" to "algoliasearch"? The angular module name export is "algoliasearch" not "algoliaSearch".

Also I can help you more if you can provide me the commands to run in the test project you did.

Thanks

**Comment by vvo** [comment]
@aslam reopen is you still have the issue, with more data
