### ISSUE TITLE
Autocomplete Tutorial uses Pre 0.11 TypeAhead.js 

### ISSUE THREAD

**Issue by joshuapinter** [algolia/algoliasearch-client-js#171]
https://www.algolia.com/doc/tutorials/multi-auto-complete

This tutorial still uses the pre-0.11 TypeAhead.js and makes use of the `ttAdapter()`, which has been removed from the latest version of TypeAhead.js. 

I'm trying to update our `typeahead.js` and our `alogliasearch-client.js` but finding it difficult to see what needs to be changed. 

Thanks!

Josh

**Comment by redox** [comment]
Oh yeah, good catch; we actually need to use [autocomplete.js](https://github.com/algolia/autocomplete.js) now :)

**Comment by joshuapinter** [comment]
Even better. Didn't even know about that.

So that removes the need for TypeAhead.js?

**Comment by redox** [comment]
> So that removes the need for TypeAhead.js?

Yes :) Actually autocomplete.js is originally a fork of typeahead.js on which we fixed all the bugs on remote sources \o/

**Comment by joshuapinter** [comment]
Ha. Thank god. Bring it on. :)

**Comment by vvo** [comment]
I am looking into this and fixing our github example to use autocomplete.js

**Comment by vvo** [comment]
Fixed! The example in github is now using autocomplete.js, thanks

**Comment by joshuapinter** [comment]
Great! Thanks! 

Noticed a minor typo on one of the tutorials: 

"The easiest way to render such auto-completion dropdown menu is to our" <-- missing "use".

From https://www.algolia.com/doc/tutorials/multi-auto-complete#ui under Section 4 UI.

**Comment by joshuapinter** [comment]
I also noticed that the code on that tutorial has been changed to reference `autocomplete.js` but there is still use of `ttAdapter` in the code and I don't believe `autocomplete.js` uses that any longer.

Was the tutorial code updated to reflect the current version of `autocomplete.js`'s API as well?

**Comment by vvo** [comment]
Just fixed the github tutorial to use the right API: https://github.com/algolia/instantsearch.js#from-a-cdn

**Comment by vvo** [comment]
I am fixing the website also, thank you for all the feedback

**Comment by vvo** [comment]
Website was already fixed, thanks!

**Comment by joshuapinter** [comment]
:+1:
