### ISSUE TITLE
Seems that we're not using gzip with Node.js

### ISSUE THREAD

**Issue by redox** [algolia/algoliasearch-client-js#173]
I cannot find any `content-encoding` or `gzip` or `deflate` occurence so I assume we're not receiving compressed JSON answer. Am I right?

**Comment by vvo** [comment]
yes no gzip in nodejs currently, do you have an issue or a support request or just checking?

**Comment by redox** [comment]
A user spotted it and it's definitely something we want to have (we ensured we had it in all other API clients).

**Comment by vvo** [comment]
ok doing it now
