### ISSUE TITLE
The process become undefined

### ISSUE THREAD

**Issue by itnick** [algolia/algoliasearch-client-js#174]
https://github.com/algolia/algoliasearch-client-js/blob/master/src/AlgoliaSearch.js#L5

**Comment by vvo** [comment]
Hi @itnick, thanks for the issue.

Can you provide us some more context and explanations on what does not work for you, in which conditions, environments.. ?

**Comment by Bossa573** [comment]
Environment: nodejs 4.2.1, MacOS 10.9.5

`process` will become undefined after line 5, so line 8 and line 808 will never be executed
I tried adding `console.log(process)` at line 6 and it's undefined.

**Comment by vvo** [comment]
was fixed @Bossa573 and @itnick. @Bossa573 nice profile pic :D

**Comment by itnick** [comment]
Thanks a lot @vvo
