### ISSUE TITLE
Modular build

### ISSUE THREAD

**Issue by pixelastic** [algolia/algoliasearch-client-js#179]
Do you think it would be possible to split the library into modules (like `lodash` does), so we could require only the methods we need. I'm thinking for example of a front-end only build that will not need all the push, delete and browse methods.

**Comment by Jerskouille** [comment]
+:100:

**Comment by Jerskouille** [comment]
Related : https://github.com/algolia/algoliasearch-client-js/issues/127

**Comment by redox** [comment]
Not sure having a fully modular API client is required (from your Node.js backend you don't really care); but having a search-only API client would definitely be welcome to reduce the size of our frontend libraries.

**Comment by vvo** [comment]
The "search only" client can be done.

But the import {search} from client is harder I think.

Lodash has no state while the JS client has (luckily) the APPID, indexName, timeouts, retries, hosts, .. so that you do not have to pass them to every method call.

What is the usecase or what would you like to solve by having this? Filesize?

**Comment by vvo** [comment]
search only client: 12.6kb
default client: 17kb

The only true way to get a very small client is to remove the lodash dependency, that's feasible.

**Comment by pixelastic** [comment]
Yes, the main use-case was to reduce the filesize of the front-end build.

**Comment by vvo** [comment]
I will give a try to building a modern client supporting only the necessary browsers.

Which means no IE < 11, Microsoft is ending support for them in January. We will have to support them but we could provide a modern build on npm for people interested.

**Comment by vvo** [comment]
This is V4 #195
