### ISSUE TITLE
Angular module instalation through bower includes the vanilla file.

### ISSUE THREAD

**Issue by mspivak** [algolia/algoliasearch-client-js#183]
I'm not sure I'm doing it wright but I installed the module like this:

    # bower install algoliasearch --save

But the file bower includded was always `algoliasearch.min.js`, instead of `algoliasearch.angular.min.js`.

I had to modify the `bower.json` for it to work. But we all know this is nasty and will fail on update. Is there a different package I should install?

Thanks in advance.

**Comment by vvo** [comment]
Since our module supports both angular and vanilla JavaScript, there's no clear way to do so, I think there's a provided solution in here: https://github.com/algolia/algoliasearch-client-js/issues/182#issuecomment-165465838
