### ISSUE TITLE
Questions about the setting

### ISSUE THREAD

**Issue by romelgomez** [algolia/algoliasearch-client-js#185]
1) I have two type of user IDs,  facebook:10204911533563856,  b0d0d782-7fe2-4c55-8fcb-c73aab87538e, when start the request with the code below, i get AlgoliaSearchError {name: "AlgoliaSearchError", message: "filters: Unexpected token string expected numeric at col 8"} , 
I think it can be the (:) or (-), to workaround over this i have to create a reference user id like this:   
facebook10204911533563856,  b0d0d7827fe24c558fcbc73aab87538e, 

2) In base the code below and this gist https://gist.github.com/romelgomez/c98991b90fb3b57981b5 how set the setting to get only the record or publications by userID or attribute reference, i should use tagFilters https://github.com/algolia/algoliasearch-client-js#category-search-parameters

```javascript
      var client = algolia.Client('······················', '······························································');
      var index  = client.initIndex('publications');

      $scope.content = {};
      $scope.query = '';
      $scope.hits = [];

      $log.info('$scope.account.user.uid',$scope.account.user.uid);
      // facebook:10204911533563856
      // b0d0d782-7fe2-4c55-8fcb-c73aab87538e
      // AlgoliaSearchError {name: "AlgoliaSearchError", message: "filters: Unexpected token string expected numeric at col 8"}

      function search (){
        index.search($scope.query, {
            //facetFilters: 'userUid='+$scope.account.user.uid,
            filters: 'userUid='+$scope.account.user.uid,
            hitsPerPage: 25
          })
          .then(function searchSuccess(content) {
            //if(content.query !== $scope.query){
            //  search();
            //}
            $scope.content = content;
            console.log(content);
          }, function searchFailure(err) {
            console.log(err);
          });
      }

      $scope.$watch(function(){
        return $scope.query;
      },function(){
        search()
      });
```
Best regards

**Comment by pixelastic** [comment]
@romelgomez : Did you fix your issue?

**Comment by romelgomez** [comment]
Hi, @pixelastic, 

Yes, I made a mistake:

This line:
            `filters: 'userUid='+$scope.account.user.uid,`

Should be:
            `filters: 'userUid:'+$scope.account.user.uid,`

I use (:) instead of (=)
 
****************************************************************
I'm reading the docs again to improve my current settings:  

var settings = {
  attributesToIndex: ['barcode','title','unordered(description)'],
  customRanking:['desc(views)'],
  attributesForFaceting: ['categories','userID'],
  numericAttributesToIndex:['price','releaseDate']
};

The releaseDate should be numericAttributesToIndex?

![index](https://cloud.githubusercontent.com/assets/2358251/12003194/750fd5ea-aae7-11e5-9fcd-d66ca91f2c00.png)




Thanks, Best regards

**Comment by pixelastic** [comment]
Good, nice to know you found the issue :)
