### ISSUE TITLE
document.write ?

### ISSUE THREAD

**Issue by borisschapira** [algolia/algoliasearch-client-js#187]
First, again, thanks for your service and scripts :)

Is it possible to remove [this `document.write`](https://github.com/algolia/algoliasearch-client-js/blob/master/dist/algoliasearch.js#L123) from the script ?

Using `document.write` is considered a bad practice by many monitoring services.

**Comment by vvo** [comment]
Hey hi! The document.write is only here for weird legacy usage of the script and is almost never triggered. We may remove it in 2016 if no more needed by any of our users.

Can you give more info on how its triggering smg bad for you?

**Comment by vvo** [comment]
The document.write is necessary for legacy compatibility with the jsdelivr.com/latest/ usage. It was introduced when we created the v3 of the client. Our users that were using /latest/ would have received the v3 client while they are using v2.

So we put this layer and we will remove it someday. Most probably this year, by manually contacting some of the last clients using /latest/.
