### ISSUE TITLE
How to set search parameter dynamically in instantsearch

### ISSUE THREAD

**Issue by sohamchak** [algolia/algoliasearch-client-js#193]
How to set search parameter dynamically in instantsearch.js. I am using urlSync : false but in save search result if I need to save my search result then should I turn urlSync : true ? If I turn it then how I will set search param urlSync dynamically ?

**Comment by vvo** [comment]
I am sorry @sohamchak I did not fully get your issue, can you be more specific on your UX need so that we can focus on the UX and then how the implementation (code wise)?

Thanks

**Comment by vvo** [comment]
Also can you move the question to https://github.com/algolia/instantsearch.js/issues, thanks
