### ISSUE TITLE
get all values of a given facet

### ISSUE THREAD

**Issue by VonD** [algolia/algoliasearch-client-js#197]
Hi,

Is there a way to get all values of a given facet in the search response ? I seem to get all of them if I don't specify any `facetFilters`, and a small subset of them otherwise. The documentation does mention this might be not exhaustive, but my index contains only 9 records, so I doubt that this is the reason.

Is it the way the client is supposed to work ? Or am I doing something wrong ? Here's what my data looks like : 

```es6
{
    ...otherProps,
    offerCatalog: {
        "0": ["0", "2", "4"],
        "1": ["0 > 0", "0 > 4", "2 > 2", "2 > 5", "4 > 3"]
    }
}
```

The following query returns me all the facets values with their count :

```es6
{
    facets: ["offerCatalog.0", "offerCatalog.1"]
}
```

Both the following queries return me only a small subset of both `offerCatalog.0` and `offerCatalog.1` facets values : 

```es6
// First query
{
    facets: ["offerCatalog.0", "offerCatalog.1"],
    facetFilters: ["offerCatalog.0:0"]
}
// Second query
{
    facets: ["offerCatalog.0", "offerCatalog.1"],
    facetFilters: ["offerCatalog.0:0", ["offerCatalog.1:0 > 1"]]
}
```

Many thanks for your help

**Comment by vvo** [comment]
> {
>     facets: ["offerCatalog.0", "offerCatalog.1"],
>     facetFilters: ["offerCatalog.0:0"]
> }

This is expected that the API in this case will only send you back objects having the "offerCatalog.0" field containing the value "0". Is that what you get?

> facetFilters: ["offerCatalog.0:0", ["offerCatalog.1:0 > 1"]]

Can you explain to me the underlying query/filter you want to do? This one means: "offerCatalog.0 is `0` AND offerCatalog.1 is `0 > 1`"

**Comment by vvo** [comment]
What you are looking for is the helper https://github.com/algolia/algoliasearch-helper-js
