### ISSUE TITLE
jsdelivr links broken

### ISSUE THREAD

**Issue by vincentwoo** [algolia/algoliasearch-client-js#199]
https://cdn.jsdelivr.net/algoliasearch/3.12.0/algoliasearch.min.js gives File not found

**Comment by vvo** [comment]
Indeed, just wondering where did you find this link?

**Comment by vincentwoo** [comment]
I read the alarming issue https://github.com/algolia/algoliasearch-client-js/issues/92, clicked on your link (jsdelivr.com), typed in algolia, and tried the first link I saw.

**Comment by vvo** [comment]
Yes this is now reported at the jsdelivr level

**Comment by vvo** [comment]
now fixed, sorry for that
