### ISSUE TITLE
get actual API request

### ISSUE THREAD

**Issue by istopopoki** [algolia/algoliasearch-client-js#200]
Hello,
All your API calls are wrapped. When using your js library, is there a way to build the algolia search request, but instead of sending it to your server, just get access to it ?
thanks for your help.

**Comment by vvo** [comment]
Do you need help in the end? Not sure to have fully understood your question

**Comment by vvo** [comment]
> All your API calls are wrapped.

What do you mean?

**Comment by istopopoki** [comment]
I was trying to get access to the details of the request issued by your js code. In the end, some request like this :

https://c4-fr-2.algolianet.com/1/indexes/myindex?x-algolia-api-key=mykey&x-algolia-application-id=myApp&x-algolia-agent=Algolia%20for%20vanilla%20JavaScript%203.7.5&query=voiture&getRankingInfo=1&facets=*&attributesToRetrieve=*&highlightPreTag=%3Cem%3E&highlightPostTag=%3C%2Fem%3E&hitsPerPage=12&facetFilters=[]&maxValuesPerFacet=10

is generated by the code, even if we can't see it. I was just wandering if there was a way to get this information using your js client ?
Thanks Vincent.

**Comment by vvo** [comment]
Yes that's a very good point: being able to have more debugging details.I will look at it in the next major version.

If you are in the browser, to activate debug in a console, you can do:

```js
localStorage.debug = 'algliasearch*';
```

If you are in node.js script, you can do:

```js
DEBUG=algoliasearch* node program.js
```

both will activate a verbose debugging.

I will try to get an API entry to get the underlying request that would be generated maybe?

**Comment by istopopoki** [comment]
sounds great !
I'll reopen my issue so I can get an update when you do it.
Thanks a lot

**Comment by vvo** [comment]
I updated my comment, tell me if you are able to activate the debugging, also what's your usecase to be able to see the underlying rest call?

**Comment by istopopoki** [comment]
I'll try the debugging mode.
I'm afraid the usecase was just curiosity...

**Comment by vvo** [comment]
Nothing to solve here, closing
