### ISSUE TITLE
Empty Request Response!

### ISSUE THREAD

**Issue by rsflow** [algolia/algoliasearch-client-js#203]
Hey @vvo ,

So here is where RN should check network connectivity. 
Now in the simulator ``isConnected`` is always `true` and the call get's through even if there is no network. But this could happen on a real device too.

```js
NetInfo.isConnected.fetch().done((isConnected) => {
       if (isConnected) 
             helper.search()
})
```
Is there something I can do to stop the bad response to be parsed to JSON and not get the error?

Thank You!

**Comment by vvo** [comment]
@DHidee66 The request implementation for the React native build is here: https://github.com/algolia/algoliasearch-client-js/blob/master/src/reactnative/builds/algoliasearch.reactnative.js

We did a blogpost about it: https://blog.algolia.com/how-we-updated-our-js-libs-for-react-native/

What I would suggest is checking the connection state in the react native build if feasible and then send an error to the caller.

In the browser when there's no network you will most probably get an error event on the XHR object. Maybe that's a failure of React Native here?

In any case, you can submit a PR where you checked in React Native that it's working.

**Comment by vvo** [comment]
Please reopen if you have found a workaround/more issues
