### ISSUE TITLE
Switch to "phantomjs-prebuilt"

### ISSUE THREAD

**Issue by kopertop** [algolia/algoliasearch-client-js#209]
Per: https://www.npmjs.com/package/phantomjs

"phantomjs" has been moved to "phantomjs-prebuilt".

**Comment by vvo** [comment]
@kopertop Can I ask you how did you discover this? Did you stumble on a bug somehow with algoliasearch-client-js?

Thanks

**Comment by kopertop** [comment]
I was tracking down a build error related to an old version of phantomjs, so I ended up searching through all of my npm dependencies to find what packages still used the old version.
This turned out to actually just be a temporary error downloading phantomjs from the server, but I thought I would still share it with you since I had discovered it. Not a high priority fix but should be simple.



On Wed, Mar 23, 2016 at 2:40 AM -0700, "Vincent Voyer" <notifications@github.com> wrote:












@kopertop Can I ask you how did you discover this? Did you stumble on a bug somehow with algoliasearch-client-js?



Thanks

**Comment by vvo** [comment]
Will change to phantomjs-prebuilt, thanks for this!

**Comment by vvo** [comment]
It was already done in develop, will release

**Comment by vvo** [comment]
released 3.13.1 but you should not get phantomjs installed still because of algoliasearch: it's a dev dependency
