### ISSUE TITLE
"objectID" attribute included in retrieved attributes even when attributesToRetrieve does not specify it

### ISSUE THREAD

**Issue by kylegibson** [algolia/algoliasearch-client-js#210]
Version 3.12.0

I have the `attributesToRetrieve` parameter configured to only include a limited specified number of attributes. That works as expected. However, in addition to the list attributes, the `objectID` is also included. I would prefer to not include the `objectID`. How can I do this?

If it's not possible to exclude this parameter, I suggest the documentation be updated to indicate that this attribute will be included regardless.

**Comment by vvo** [comment]
I do think this attribute is always retrieved

**Comment by vvo** [comment]
This is by design, we will update the documentation
