### ISSUE TITLE
Race condition - clearCache not working

### ISSUE THREAD

**Issue by parliament718** [algolia/algoliasearch-client-js#212]
I'm experiencing a race condition when querying my index, even if I use index.waitTask()

```

//node.js backend endpoint to "create" room, index in Algolia
app.post('/api/room', function(request, response) {
   var room = request.body.room;
   roomsIndex.addObject(room, function(error, content) {
      roomsIndex.waitTask(content.taskID, function() {
         room.id = content.objectID;
         response.status(201).send(room);
      });
   });
});

```

On the front-end, I wait for the response, and push the room into my Firebase data store.

```

$http.post('api/room', room).then(function(indexedRoom) {
     console.log('indexed room in Algolia. Pushing to Firebase');
     $firebase.child('rooms').push(indexedRoom.data);
 })

```

Then somewhere else on my front-end I listen to the room being added to Firebase, and re-query the Algolia index.

```
$firebase.child('rooms').on('child_added', function(snapshot) {
       $algolia.roomsIndex.clearCache();
       $algolia.roomsIndex.search(...);
});

```

However, when I requery the index, I don't get the newly indexed room back. If I query again shortly after,  then it appears. So there seems to be race condition, however I do not see how that could be caused by my own code, unless `roomsIndex.waitTask()` or `roomsIndex.clearCache()` are not working correctly.

**Comment by vvo** [comment]
Hi, thanks for reporting this.

Can you reduce the race condition test case to only using Algolia? It would help debug this one.

Here we have multiple parts that could produce a bad behavior:
- angular http service
- firebase api

So it would be better to be able to prove that using the raw JS api client like you do you can find a race condition, and if you cannot then move to the next stack and on and on.

**Comment by parliament718** [comment]
There is no problem with the Algolia only test case. I'm not sure exactly what it was but it seems that it had to do with front-end promise handling. I moved the call to clearIndex() right before search() and it worked.

**Comment by parliament718** [comment]
As a side note, can you please answer the question:

Is calling clearIndex() from the front end lib the same as calling clearIndex() on the backend? In other words, if I call it on the backend when the room is index, and not on the front-end, will the front-end still pull from cache?

**Comment by vvo** [comment]
So the "cache" we talk about in our libraries is only JavaScript cache, it's a simple object inside the browser/nodejs server that will avoid doing searches that were already done.

This is not an "Algolia cache" per se. It's just the API client own cache.

If you search for "bananas" on the frontend or backend, then when the response has come, search again for "bananas", no request will be done BUT if you called "clearCache()" right before doing the second search.

Is that more clear?
