### ISSUE TITLE
Aroundlatlang saying 400 bad request

### ISSUE THREAD

**Issue by prspace** [algolia/algoliasearch-client-js#213]
var coords = pos.coords;
            var APPLICATION_ID = algoliaCredential.appId;
            var SEARCH_ONLY_API_KEY = algoliaCredential.searcKey;
            var spacificAlgolia = algoliasearch(APPLICATION_ID, SEARCH_ONLY_API_KEY);
            var queries = [{
                indexName: 'listings',
                params: {
                    hitsPerPage: 10,
                    aroundLatLng: [coords.latitude, coords.longitude]
                }
            }];
            spacificAlgolia.search(queries, function (err, content) {
                console.log(content, err);
            })
No results coming... it's saying "Invalid number of values...aroundLatLng parameters"

**Comment by redox** [comment]
Arg, you should use `aroundLatLng: coords.latitude + ',' + coords.longitude` (as a string).

Maybe we could ask our backend team to work on supporting an array here -> makes a lot of sense.

**Comment by prspace** [comment]
It works! thank you. And of course array syntax's is better.
