### ISSUE TITLE
How to anticipate breaking changes ?

### ISSUE THREAD

**Issue by vincent-guesnard** [algolia/algoliasearch-client-js#214]
Hello,

I've found an issue while deploying algoliasearch.js 3.13.1 on jquery 2.2.3.

This old code doesn't work any longer : 

var client = $.algolia.Client(btw_algolia_application_id, btw_algolia_api_key);
var index = client.initIndex(btw_algolia_index1);
index.search($inputfield.val(), {hitsPerPage: 5})
                        .done(searchCallback)
                        .fail(function (content) {
                            console.log('Error', content);
                        });

Solved by the following code : 

var btw_algolia_client = algoliasearch(btw_algolia_application_id, btw_algolia_api_key);
var btw_algolia_index = btw_algolia_client.initIndex(btw_algolia_index1);
btw_algolia_index.search($inputfield.val(), {hitsPerPage: 5})
                        .then(searchCallback, function searchFailure(err) {
                            console.log('Error', err);
                        });

That's not impossible that i miss this breaking change, and i apologize if it's the case.

Else, in the future, is there an exhaustive changelog somewhere, to anticipate this kind of problems (which took me 30 minutes to solve instead of 30 seconds ?)

Thanks

(And your tools remains amazing !)

Best regards,

Vincent GUESNARD

**Comment by vvo** [comment]
Thanks for reporting this.

So the only thing in your environement that changed and triggered a bug is that you upgraded algoliasearch to v3.13.1?

**Comment by vvo** [comment]
I just did a test on jsfiddle with the latest jquery v2 and algoliasearch: it works. Maybe have a look and let me know: https://jsfiddle.net/9kejrgcj/

**Comment by vincent-guesnard** [comment]
I've upgraded algoliasearch to 3.13.1, and JQuery, from 2.2.0 to 2.2.3

1. It throwns : Uncaught TypeError: Cannot read property 'Client' of undefined on this decleration :
var client = $.algolia.Client(btw_algolia_application_id, btw_algolia_api_key);

So i update to : 

var client = algoliasearch(btw_algolia_application_id, btw_algolia_api_key);

2. it throwns : Uncaught TypeError: index.search(...).done is not a function on this decleration : 

index.search($inputfield.val(), {hitsPerPage: 5})
                        .done(searchCallback)
                        .fail(function (content) {
                            console.log('Error', content);
                        });

Seems that .done() and .fail() functions are no longer supported.

If it helps.

My problem is solved, my question was only about anticipating this in the futur.

**Comment by vvo** [comment]
> My problem is solved, my question was only about anticipating this in the futur.

Can you have a look at my jsfiddle? https://jsfiddle.net/9kejrgcj/ It's the same code as you and it's working so maybe there's something different in your setup?

**Comment by vvo** [comment]
You need to use https://cdn.jsdelivr.net/algoliasearch/3/algoliasearch.jquery.min.js that's very important maybe you inserted https://cdn.jsdelivr.net/algoliasearch/3.13.1/algoliasearch.min.js which is not the jquery build?

**Comment by vincent-guesnard** [comment]
Ok here is my mistake ! Seems that i need to sleep better next night ^^

Sorry about this wasting time.

**Comment by vvo** [comment]
Great that we solved this quickly! happy coding :)

**Comment by vvo** [comment]
And sleepling :sleeping:

**Comment by vincent-guesnard** [comment]
Thank you very much, your help, as always, was flawless :)
