### ISSUE TITLE
Client is heavyweight

### ISSUE THREAD

**Issue by anaibol** [algolia/algoliasearch-client-js#215]
Hi, I noticed that adding the client to my application added 70kb to the minified build. Is that normal?
Could we split the client to have only the minimal code on the client?

**Comment by vvo** [comment]
Hi @anaibol this is a planed evolution of te JS client yes but requires a bit more work. The current gzipped size of the client is aroud 19kb.

This is not so much but still a bit heavy I understand.

Watch the github repository to be notified once available.

**Comment by vvo** [comment]
Do you need a search-only client is that it?

**Comment by anaibol** [comment]
@vvo yes! Would you recommend using directly the REST API via HTTPS calls as a lightweight solution?

**Comment by vvo** [comment]
@anaibol I am currently building a lite client, thanks for opening the issue

**Comment by anaibol** [comment]
Great!

**Comment by vvo** [comment]
This will be released monday @anaibol, good?

**Comment by anaibol** [comment]
Very good! Bon weekend!

**Comment by anaibol** [comment]
Hi @vvo! I can't currently find algoliasearch/dist/algoliasearchLite. Is it on the current build?

**Comment by vvo** [comment]
Not yet, should be done today. Had to delay it a bit

**Comment by anaibol** [comment]
Ok many thanks!
