### ISSUE TITLE
index.getObjects throws error when passed empty array

### ISSUE THREAD

**Issue by vincentwoo** [algolia/algoliasearch-client-js#226]
I'd expect `index.getObjects([], function(...` to simply return an empty list. Currently it gives a `400 Bad Request` because the library sends an HTTP POST with `{"requests":[]}:` to `/1/indexes/*/objects`.

**Comment by vvo** [comment]
Hi @vincentwoo, indeed we error in this case so that developers using Algolia can discover bugs like calling a method with empty arguments in their own data.

Here there's no need to call getObjects if you pass an empty array.

We try not to be too magical oterwise we might hide bugs from the caller.

**Comment by vincentwoo** [comment]
That's fair, but I don't really think "passing an empty list" is a "bug". I think every application that sends a dynamic number of elements has to deal with the 0 case. In this case 0 inputs = 0 outputs is more expected and not magical at all. 1 input = 1 output, 2 inputs = 2 outputs, but 0 inputs = ERROR is actually stranger to me.

**Comment by vvo** [comment]
We try to map closely the REST API server and indeed currently it sends an error when you call it with an empty list of requests for getObjects().

We could change that at the API client level but that would introduce a different behavior between the API client and the REST API, that we do not want to have it.

Then, should the REST API return an empty array when asking for an empty list of objects? We will consider that in next versions but for the current version this would be a breaking change.

**Comment by vvo** [comment]
We are not gonna introduce differences between the API client and the API server behavior, we are just a raw API client.
