### ISSUE TITLE
getLogs method doesn't support the type parameter

### ISSUE THREAD

**Issue by Nagriar** [algolia/algoliasearch-client-js#232]
In the readme, two parameters other parameters are available:
<img width="891" alt="capture d ecran 2016-05-05 a 08 55 55" src="https://cloud.githubusercontent.com/assets/2361099/15037890/2a8e9aa4-129f-11e6-94ca-4dcf1b41d95e.png">

but those two parameters are available in the prototype of getLogs method:

    AlgoliaSearch.prototype.getLogs = function(offset, length, callback)

**Comment by vvo** [comment]
Fixed, released in 3.15.1
