### ISSUE TITLE
Document lite client

### ISSUE THREAD

**Issue by oncletom** [algolia/algoliasearch-client-js#233]
'cause from a browser perspective it might be the biggest use case.

And I discovered it because `CHANGELOG`.

**Comment by vvo** [comment]
Indeed I added the underlying documentation but we need to update READMEs

**Comment by vvo** [comment]
https://github.com/algolia/algoliasearch-client-readme-generator/pull/42

**Comment by oncletom** [comment]
Perfect thanks :-)

**Comment by vvo** [comment]
fixed

**Comment by vvo** [comment]
https://github.com/algolia/algoliasearch-client-js#search-onlylite-client
