### ISSUE TITLE
JSONP fallback is too aggressive & wrong when angularJS

### ISSUE THREAD

**Issue by redox** [algolia/algoliasearch-client-js#250]
In the following code, we assign the `tries` variable to `Infinity` to force the JSONP retry. But that's wrong:
 - when using the Angular build, `hasFallback` is false (because `client._useFallback` is undefined) and we're therefore not retrying
 - when there is any network error on 1 host, we need to retry on the others without going for JSONP

```js
      // stop the request implementation when:
      if (
        // we did not generate this error,
        // it comes from a throw in some other piece of code
        err instanceof errors.Unknown ||

        // server sent unparsable JSON
        err instanceof errors.UnparsableJSON ||

        // max tries and already using fallback or no fallback
        tries >= client.hosts[initialOpts.hostType].length &&
        (usingFallback || !hasFallback)) {
        // stop request implementation for this command
        err.debugData = debugData;
        return client._promise.reject(err);
      }

      if (err instanceof errors.RequestTimeout) {
        return retryRequest();
      } else if (!usingFallback) {
        client.hostIndex[initialOpts.hostType] = ++client.hostIndex[initialOpts.hostType] % client.hosts[initialOpts.hostType].length;
        // next request loop, force using fallback for this request
        tries = Infinity;
      }

      return doRequest(requester, reqOpts);
    }
```

**Comment by redox** [comment]
OK, I tried to fix the issue but I'm struggling with the tests, cannot make them pass :/

**Comment by pixelastic** [comment]
Do you think it might be linked to #251? The user I had that was having intermittent connections to `algolia.net` instead of `algolianet.com` was using the angular build.

**Comment by vvo** [comment]
One thing I do not get is that angular build has jsonp fallback, we have a test for it and useFallback is true by default

**Comment by vvo** [comment]
Also we try jsonp asap because blocked xhrs can be immediate or after timeout (invisible).

As soon as we are in jsonp if theres a network error we try other hosts.

**Comment by vvo** [comment]
We could still try all hosts before using jsonp like you said. We have low data on the "blocked xhrs" behavior/cases. I will do this when I am back.

**Comment by redox** [comment]
> One thing I do not get is that angular build has jsonp fallback, we have a test for it and useFallback is true by default

I didn't investigate too much, but for sure if it has the fallback it's not working :)

> We could still try all hosts before using jsonp like you said. We have low data on the "blocked xhrs" behavior/cases. I will do this when I am back.

Yeah I think we should just iterate over all hosts every times; no need to "optimize" anything doing JSONP next.

**Comment by vvo** [comment]
Are we using read and write timeouts with different values on the website? I remember an issue on the website where we set big timeouts and thus the dashboard would fail to load. Js client now have read and write timeouts features

**Comment by vvo** [comment]
I was not able to reproduce this in 3.14.1 by changing -dsn.algolia.net to -dsn.algolia.biz and using the angular examples => it worked.

We may be missing something here.

**Comment by vvo** [comment]
Issue was: https://github.com/algolia/algoliasearch-client-js/pull/262
