### ISSUE TITLE
DNS fallback resolution not working correctly

### ISSUE THREAD

**Issue by pixelastic** [algolia/algoliasearch-client-js#251]
Following the recent NSOne DNS attack, we had a few customers reaching to use because their search wasn't working. For most of them it was because they were using an old API client version without the DNS fallback mechanism.

But for a few of them, that were using the very latest (3.14) version, they still had issues where some requests were targetting `algolia.net` and others `algolianet.com`. One user confirmed that reverting to 3.13 fixed the issue, the other monkey patched the code to force the `algolianet.com` endpoint.

I haven't been able to reproduce it on my side (DNS correctly working for me), but we did change this code in between those two releases, so we might have introduced a bug. I will dive more deeply into it as soon as I can but I'm taking a 11h flight tomorrow morning so not sure I'll be able to really focus on it.

All help is thus welcome into finding the bug and fix it as fast as we can.

**Comment by vvo** [comment]
What changed in 3.14 was that we reintroduced hist shuffling for algolianet.com but I doubt this is the issue here.

"Linked" commits:
- https://github.com/algolia/algoliasearch-client-js/commit/4ec5e6a1f8cd92924ce025d60646b3a47b7d8dca
- https://github.com/algolia/algoliasearch-client-js/commit/78e3e4cca904929018f3a1c55875fe2a2fa95b08

First commit I tested it manually with success

**Comment by vvo** [comment]
Was nsone refusing connections our timeouting while ddos? First case would trigger network errors, second one would trigger timeouts

**Comment by asurak** [comment]
Not refusing, it was timeouting. I'm preparing a domain that it will be possible to test on.

**Comment by asurak** [comment]
The domain `algolia.biz` is set to timeout for whatever you ask it - `latency-dsn.algolia.biz` - and simulated DNS provider under attack
