### ISSUE TITLE
index.search returning no hits (whilst nbHits is positive)

### ISSUE THREAD

**Issue by gwendall** [algolia/algoliasearch-client-js#271]
As the title says, I am running a simple search using ```index.search``` (no particular option), which returns something like:

```javascript
{
  hits: [],
  nbHits: 4
}
```

How can I access those hits ?

**Comment by vvo** [comment]
Hi @gwendall this shoud not happen of course, can you send an email to support@algolia.com with more details? Or if everything is public, a simple jsfiddle demonstrating the issue would be awesome.

We need more details here.

**Comment by vvo** [comment]
Closing, need more details

**Comment by elitan** [comment]
Hi, I am currently receiving the same error. I sent you a message to the support email above.

**Comment by elitan** [comment]
Oups, happend when I tried to view page 1 when there was only one page in the results (pages starting at 0). I should have sent page=0, not page=1.
