### ISSUE TITLE
Cannot find module 'crypto'

### ISSUE THREAD

**Issue by Grep-Juub** [algolia/algoliasearch-client-js#291]
Hi guys,
I'm using Algolia since yesterday and I've got some good results when using it with one of my project wich is in React+Meteor, but I can't give the same magic tool to an older app of mine also in Meteor.
I use the lastest versions of **meteor** (1.3.3-1) and **algoliasearch** lastest update from yesterday 3.16.1.

And when I start my app, I've got this: 
` Cannot find module 'crypto' `
[More here](http://i.imgur.com/xzqffkf.png?1)

If you have any idea ?
Thanks

**Comment by vvo** [comment]
Hi, can you try:

```js
import algoliasearch from 'algoliasearch/src/browser/builds/algoliasearchLite.js';
```

Relevant discussion: https://github.com/algolia/instantsearch.js/issues/1024
Relevant discussion: https://github.com/meteor/meteor/issues/6890

**Comment by Grep-Juub** [comment]
Ok so I've managed to make it work, the problem was with Meteor I've put the import in file wich was in `lib/` folder at the root of my project, so I made some Meteor method to use it only on the server side.

**Comment by RakanNimer** [comment]
Had same issue in react-native environment.  (For future reference)

Fixed by using @vvo's suggestion.

Cheers !
