### ISSUE TITLE
Named argument for js client.

### ISSUE THREAD

**Issue by fulmicoton** [algolia/algoliasearch-client-js#3]
This issue is not exactly an issue, but I thought it might be a good thing to raise the subject before the client gets very popular. Have you thought of using a dictionary as an argument for the creation of the Algolia object?

As a benefit, 

1) you could give the JSON representation of this dictionary in all the place where you present the user credentials. It will be a valid literal, ready for copy-paste for JS, NodeJS but also python !

2) it will make it easier for you to grow the API options.

3) it will help people, as their configuration will probably, be in one way or another, serialized or defined beforehands in their code.

**Comment by vvo** [comment]
see #40
