### ISSUE TITLE
Too many messages being logged

### ISSUE THREAD

**Issue by fabiozaffani** [algolia/algoliasearch-client-js#301]
Hi,

Due to the current nature of my app (integration between firebase and algolia) i'm currently getting my console flooded with all the algoliasearch module updates (related to index)

It would be good great to have an option to disable this, otherwise the only other solution I though would be to always comment/uncomment the code that call's the algolia indexing.

Best regards

**Comment by vvo** [comment]
Hi @fabiozaffani, can you provide me some examples of the logging done by Algolia module?

We only do some logging when NODE_ENV=development, yes we should make this optionnal or at least reduce the noise.

**Comment by fabiozaffani** [comment]
Hi @vvo , thanks for the fast reply.

And that's exactly the issue, in the development environment. If you have many items being updated/synced with algolia the log list grows really bi. I think it would be a good option to have it come with the logs being recorded by default but with an option to disable it, like a flag in the initialization config object or something.

Bellow are some of the messages (getting hit by like 30/40 each time I updated anything in the code)

`Tue, 19 Jul 2016 14:08:12 GMT algoliasearch:/1/indexes/localhost/-JyucYch6Earl3kJDtC5 received response: statusCode: 200, computed statusCode: 200, headers: {"server":"nginx","date":"Tue, 19 Jul 2016 14:08:11 GMT","content-type":"application/json; charset=UTF-8","content-length":"96","connection":"keep-alive","access-control-allow-origin":"*","cache-control":"no-cache"}`

**Comment by samueldr** [comment]
A work-around, for until an option is available, can be made using the filters of the developer tools.

Using this regex:

    ^[^algoliasearch]

Explanation of the regex:
  * Anything starting with, `^`
  * something else than the string *algoliasearch*. `[^algoliasearch]`

![screenshot](https://i.imgur.com/6UOnIj6.png)


Hope this helps!

**Comment by vvo** [comment]
released 3.18.0 with a fix, only activates debug mode when NODE_ENV is debug
