### ISSUE TITLE
getObject on lightweight algolia

### ISSUE THREAD

**Issue by acemtp** [algolia/algoliasearch-client-js#308]
Hi Vincent,

I know algolia lightweight version has to be light but it would be useful to have getObject() in it too.

Adding it will really increase the size of the lite package?

**Comment by vvo** [comment]
Just added it in 3.18.0, let me know

**Comment by acemtp** [comment]
Cool. Do you know how long does it take to spread to jsdelivr? https://cdn.jsdelivr.net/algoliasearch/3/algoliasearchLite.min.js

**Comment by vvo** [comment]
It's now available, refresh
