### ISSUE TITLE
Wrong facets totals

### ISSUE THREAD

**Issue by mgtitimoli** [algolia/algoliasearch-client-js#310]
Hi everyone,

I'm experiencing a weird error with facets totals. I have an index which has one array field that contains objects, and I'm using the keys of those ones as facets:

**Sessions of one object present in the index** 
```javascript
  "sessions" : [{
    "dayName" : "Wednesday",
    "timePeriod" : "Evening",
    "asString" : "Wednesday Evening"
  }, {
    "dayName" : "Tuesday",
    "timePeriod" : "Morning",
    "asString" : "Tuesday Morning"
  }, {
    "dayName" : "Thursday",
    "timePeriod" : "Afternoon",
    "asString" : "Thursday Afternoon"
  }],
```

**Index facets**
![image](https://cloud.githubusercontent.com/assets/4404683/17260411/9c263f6a-55a6-11e6-8b42-f5af680e860b.png)

I'm using `sessions.dayName`, `sessions.timePeriod` and `sessions.asString` for faceting. All good with this, I was able to configure everything on the dashboard, the problem appears when I use the client to call the API, let me share some screenshots so you will be able to see it by yourselves:

**Querying the API using the client**
![image](https://cloud.githubusercontent.com/assets/4404683/17259576/8ae94304-55a2-11e6-9405-22e2c6fc6669.png)

**Facets Totals I got in the response**
![image](https://cloud.githubusercontent.com/assets/4404683/17263646/72aa93fe-55b8-11e6-80fe-49ef78562205.png)

I was expecting for example `sessions.dayName` `Monday` total to be the sum of all the totals of `sessions.asString` that contain `Monday`, so basically the following test is failing:

```javascript
it("should match dayName total with the sum of its asString entries ", () => {
    // it can be any day, the test should pass for all of them
    const dayName = 'Monday';

    const daySessionAsStringTotalsSum = Object
        .entries(result.facets["sessions.asString"])
        .filter(([curFacet]) => curFacet.includes(dayName))
        .reduce((totalsSum, [, curTotal]) => totalsSum + curTotal, 0);

    const dayTotal = result.facets["sessions.dayName"][dayName];

    const expected = true;
    const actual = dayTotal === daySessionAsStringTotalsSum;

    assert.equal(actual === expected);
});
```

It's worth noting that if I disable `aroundLatLngViaIP` parameter, results are correct. I have also tested sending different values in aroundRadius to see if this changes something, but no, the same, totals don't match, only switching off  `aroundLatLngViaIP` corrects the results.

**Query without `aroundLatLngViaIP`**
![image](https://cloud.githubusercontent.com/assets/4404683/17263752/1948b4ca-55b9-11e6-851c-321e873fa1ef.png)

**Results without `aroundLatLngViaIP`**
![image](https://cloud.githubusercontent.com/assets/4404683/17263781/44a6d57a-55b9-11e6-86be-a1d387d47b91.png)

(As you can see, these ones meet the condition I've previously written)

Any clue of why this is happening? Maybe I'm missing something?

Thanks!

**Comment by tlvenn** [comment]
Bonjour @vvo, any idea for us of what might be happening ? Thanks !

**Comment by vvo** [comment]
Hi @mgtitimoli and @tlvenn, thanks for reporting this. This look a rather advanced example and it needs to be cleaned off a little before we can start debugging.

As this seems to not be related to the JavaScript client in particular (but more of an understanding of facets and requests) I advise you to send a message to support@algolia.com defining your problem. If you are able to reduce the index size to something smaller demonstrating the issue of counts that would help a lot the debugging. Thanks!
