### ISSUE TITLE
How to get all the results

### ISSUE THREAD

**Issue by janesconference** [algolia/algoliasearch-client-js#32]
Hello, I read in the docs that:

>query: (string) The instant-search query string, all words of the query are interpreted as prefixes (for example "John Mc" will match "John Mccamey" and "Johnathan Mccamey"). ***If no query parameter is set, retrieves all objects***

However, when I search like this:

`index.search(undefined, searchCallback, {facets: '*', page: pageNum});`

It will search for the literal word `'undefined'`. Same for `'null'`.

Digging a bit on the code, I found that algoliasearch.js, line ~1206, does:

`var params = 'query=' + encodeURIComponent(query);`

(please mind I'm using v2.9.1).

Now, I didn't go to the spec, but it seems that `encodeURIComponent(undefined)` returns the string `'undefined'`, at least in the latest Chrome. This results in searching my Algolia index for that word, instead of retrieving all the results, as I intended to.

Is there a special syntax for retrieving all the results or is it a bug?

**Comment by vvo** [comment]
@janesconference Fast answer: You should be able to use:

```js
index.search('', searchCallback, {facets: '*', page: pageNum});
```

About the:

> query: (string) The instant-search query string, all words of the query are interpreted as prefixes (for example "John Mc" will match "John Mccamey" and "Johnathan Mccamey"). If no query parameter is set, retrieves all objects

I will work on it to reflect the documentation so every time query is not available (undefined, null, ''..), you get all results.

Let me know if the quick solution works.

**Comment by janesconference** [comment]
@vvo: Tried it already, but it doesn't work.

It sends:

`http://zrgf6geoq8-dsn.algolia.net/1/indexes/publicLayers?callback=algoliaJSONP_1&X-Algolia-Application-Id=<myId>&X-Algolia-API-Key=<myKey>&query=&facets=*&page=0`

and Algolia returns a 400.

Even 

`index.search('""', searchCallback, {facets: '*', page: pageNum});`

does not work (puts `%22%22` in the query, and the servers complains with a 400 again)

**Comment by vvo** [comment]
@janesconference can you come to the support so that I can chat with you and sort this out? I want to build a jsfiddle with you to see what's wrong.

To initiate a live support, go to your [support dashboard](https://www.algolia.com/support) and click on the bottom right on "Need help", I'll be there waiting.

**Comment by janesconference** [comment]
For future reference to other users:
`index.search('""', searchCallback, {facets: '*', page: pageNum});` 
works perfectly, but needs at least one search parameter / filter to avoid the `400` *if the distinct option is on* (so, pretty much a corner case).

Thanks to @vvo for identifying the problem and giving alternatives!

**Comment by vvo** [comment]
For reference, an empty query AND a distinct parameters are no compatible: https://github.com/algolia/algoliasearch-client-js#distinct-parameter

We need at least one search criteria to be able to use "distinct" on queries. This is a good thing: 

If your usecase is building the "first page" of your application, where you want to show some results but without any search criteria, adding a search criteria would help.

Say you are building a contact list, you might want to show the most frequently viewed contact, if your index contains a `viewCount` per contact, then use it like this:

```js
index.search('', function() {}, {page: 0, numericFilters: ['viewCount>0']});
```

Then you get the contacts that were seen at least once.
