### ISSUE TITLE
Object not updating

### ISSUE THREAD

**Issue by brianjd** [algolia/algoliasearch-client-js#321]
I'm currently using the client to hook into my model/object lifecycle, but updates aren't working. Currently, I'm calling `saveObject` and passing it the necessary arguments (a document with the necessary objectID & callback), no error is returned, and I receive the taskID from Algolia.  But the document doesn't update.  I thought maybe I had the wrong API keys, and therefore manipulating the wrong index, but that isn't the case.  Any thoughts?

**Comment by vvo** [comment]
Hi @brianjd, we are not aware of any issue using saveObject to update objects.

If there's no error and you receive the taskID then you are all good and once the taskID is done (use waitTask for that: https://github.com/algolia/algoliasearch-client-js#wait-for-operations---waittask) then the object should be updated.

I would advise your to double check everything and if it's still not working to send an email to support@algolia.com, mentioning this issue and my name: Vincent.

Then we will work on it privately, using your API keys and trying to reproduce the issue.

Let me know how it goes.

**Comment by brianjd** [comment]
@vvo Used waitTask, still no error, still no update.  Sent email.  

Thanks
