### ISSUE TITLE
[Question] deleteByQuery just with params?

### ISSUE THREAD

**Issue by Kikobeats** [algolia/algoliasearch-client-js#325]
Can I perform a delete query just for a determinate object with specific params?

For example:

```js
// with query parameters
index.deleteByQuery({
  type: 'table'
}, function(err) {
  if (!err) {
    console.log('success');
  }
});
```

**Comment by vvo** [comment]
Ultimately this should work but today it does not, you will have to:

```js
index.deleteByQuery('', {
  type: 'table'
}, function(err) {
  if (!err) {
    console.log('success');
  }
});
```

Let me know how it goes.

**Comment by Kikobeats** [comment]
oh, true. thanks. One thing, if `type` is a facet and `table`an specific value, how would the query to eliminate these entities?

**Comment by vvo** [comment]
Right sorry I read too quickly, so you would have to do:

```js
index.deleteByQuery('', {
  filters: 'type=table'
}, function(err) {
  if (!err) {
    console.log('success');
  }
});
```

Have a look here: https://www.algolia.com/doc/rest-api/search#unified-filter-parameter-sql-like

**Comment by Kikobeats** [comment]
Because the value is not numerical, That's the final query:

```
index.deleteByQuery('', {
  filters: 'type:table'
}, function(err) {
  if (!err) {
    console.log('success');
  }
});
```

Thanks for all 😄

**Comment by vvo** [comment]
Oh my, weekend support is not up to week support level :D:D

**Comment by vvo** [comment]
Thanks for solving this yourself :p

**Comment by Kikobeats** [comment]
no problem!! 😄
