### ISSUE TITLE
Merge node and js version of algolia-client

### ISSUE THREAD

**Issue by bobylito** [algolia/algoliasearch-client-js#34]
In order to realise full blown hyper trendy isomorphic apps, we should be able to use the same library on both side of the internet (client and server). And from what I understand, it's not only an implementation problem, it is also an API problem. The signatures being slightly divergeant in one implementation or the other which prevents us from doing a drop in replacement of the lib on each side of the wire.

**Comment by vvo** [comment]
would be feasible. will detail this in the v3 "roadmap" next week

**Comment by vvo** [comment]
see #46
