### ISSUE TITLE
Support request

### ISSUE THREAD

**Issue by DevSide** [algolia/algoliasearch-client-js#344]
https://github.com/visionmedia/debug/pull/315

This PR will close two projects/dependencies:
https://github.com/algolia/ms.js
https://www.npmjs.com/package/debug-ms-fix-yui-compressor

**Comment by vvo** [comment]
way to go if you can get it merged

**Comment by vvo** [comment]
@DevSide seems to not yet be released, let me know when new version of debug is released

**Comment by DevSide** [comment]
@vvo  yes, i will.
