### ISSUE TITLE
AlgoliaSearchHelper: Simplify the hierarchical facets refinement

### ISSUE THREAD

**Issue by redox** [algolia/algoliasearch-client-js#35]
To be able to build [such facet tree](http://jsfiddle.net/SpL3n/8/) without messy code.

**Comment by vvo** [comment]
We need to work together on what you try to accomplish, tomorrow?

**Comment by redox** [comment]
Deal!

**Comment by vvo** [comment]
Moved to algolia/algoliasearch-helper-js#24
