### ISSUE TITLE
index.getObject(myArray,... produces an Error 404

### ISSUE THREAD

**Issue by delueg** [algolia/algoliasearch-client-js#353]
As long my array has only 1 entry it is working as expected. 

But at the moment there are 2 or more entries it comes to an 404.

i realised that the system is not able to is not able to realise

algolia.net/1/indexes/myIndex/first-objectID`%2C`second-objectID?...

`{
  "message": "ObjectID does not exist",
  "status": 404
}`

algolia.net/1/indexes/myIndex/first_objectID?....

gives me no error.

**Comment by vvo** [comment]
Hi @delueg you will have to use getObjects(). We could make getObject work with arrays too in the future and basically every method working with one or more element behave the same.

Let me know how it goes.

**Comment by delueg** [comment]
Oh man.. sorry :)

**Comment by vvo** [comment]
No prob :dancer:
