### ISSUE TITLE
Get all possible values of an attribute for faceting

### ISSUE THREAD

**Issue by delueg** [algolia/algoliasearch-client-js#354]
is it possible to get all possible values of an attribute for faceting? 

for example: 

i have an attribute for faceting "gender" with entries 'male' and 'female'

what i need is some method to get this values something like
`[
'male',
'female'
]`

**Comment by delueg** [comment]
i found it. you have to add the facets:* to your params inside a search function

```
index.search('',
        {
           'facets':'*'
         },function(err, content) {
         console.log(content);
});
```

**Comment by vvo** [comment]
Great!
