### ISSUE TITLE
 2 different objects in one index

### ISSUE THREAD

**Issue by hovhannesDavtyan** [algolia/algoliasearch-client-js#363]
Can i add 2 different type of objects in one index

**Comment by vvo** [comment]
@hovhannesDavtyan Hi, can you precise a bit more what you want to achieve? You can definitely do something like:

```js
index.addObjects([{
  title: 'hello'
}, {
  name: 'hola'
}]);
```

**Comment by hovhannesDavtyan** [comment]
Thanks a lot for quick answer , i just not expected it so easy :)

Regards,
Hovhannes

2016-12-02 19:25 GMT+04:00 Vincent Voyer <notifications@github.com>:

**Comment by vvo** [comment]
Nice!
