### ISSUE TITLE
Pass the version of the client to the API.

### ISSUE THREAD

**Issue by bobylito** [algolia/algoliasearch-client-js#56]
When calling the rest API, send a new header that will state the client version. Parameter name proposition : X-algoliaclient-version

- [x] in V3
- [x] in V2

**Comment by redox** [comment]
Introducing a new `X-Algolia-ClientVersion` (or `X-Algolia-Version` ?) looks good! cc @Nagriar

**Comment by vvo** [comment]
This will help us get some stats about client version usage. It would be good to have it set in both V3 and release a new V2 (V2 branch) also.

So we can hopfully see a decrease in V2 usage.

**Comment by vvo** [comment]
This was solved in V3, we send a x-user-agent on the query string or headers (node)

**Comment by vvo** [comment]
done and released in 2.9.7
