### ISSUE TITLE
IE9 intermittently fails to execute ajax request

### ISSUE THREAD

**Issue by lukewendling** [algolia/algoliasearch-client-js#76]
Using js client v2 or v3, the search callback does not execute. I'm testing on IE9 via browserstack.com. Live search can be found at http://mytennislessons.com/search?q=Austin

I only have access to Firebug Lite in browserstack, but with that, I don't see any js exceptions. Any ideas?

Relevant snippet

```javascript
index.search('',
    { aroundLatLng: coordinates, aroundRadius: 32187, getRankingInfo: 1,
      hitsPerPage: self.perPage
    },
    searchCallback
  );

  function searchCallback(err, content) {
    alert('searchCallback'); // not executed
  }
```

**Comment by lukewendling** [comment]
Follow up: poking around in IE9 developer tools, I inspected the network traffic and see the following:

![image](https://cloud.githubusercontent.com/assets/12628/6956220/4ba5a2e8-d8b0-11e4-86fb-f2fc695e5b56.png)

The request is aborted quite quickly. There's a lot of SO chatter about aborted ajax requests in IE9 but I can't find a solution for the Algolia js client. What am I missing?

**Comment by vvo** [comment]
Thanks a lot for the detailed bug report. I will have a look today and piblish a fix accordingly. Will let you know.

**Comment by vvo** [comment]
Hi @lukewendling I found the issue and the patch is going to be released in a couple of minutes. I see you are now using /3/ on the website, does it solved the issue in IE9?

**Comment by vvo** [comment]
I added the fix to both V2 and V3, you can stick to V3 and when the script udpates your website will work on IE9. Only waiting for jsdelivr to pull the patch now

**Comment by lukewendling** [comment]
I saw the same behavior on v2 and v3.

Thanks for the quick fix.

**Comment by vvo** [comment]
Update: jsdelivr is still not up to date, expect a live fix on your website in the next day. Thanks. Sorry for the inconvenience.

**Comment by vvo** [comment]
Ok @lukewendling this is now deployed and fixed, I tested your website on IE9 and it worked.

You may need to refresh your browser cache to be able to see the difference.

Thanks a lot for your help and investigation.

Let me know if you need anything.

**Comment by vvo** [comment]
FWIW: The bug was triggered by XDomainRequest implementation. We needed to listen for all events like onerror, onload, onprogress. Even if we do not use onprogress.

Ref: https://social.msdn.microsoft.com/Forums/ie/en-US/30ef3add-767c-4436-b8a9-f1ca19b4812e/ie9-rtm-xdomainrequest-issued-requests-may-abort-if-all-event-handlers-not-specified?forum=iewebdevelopment

**Comment by lukewendling** [comment]
Thanks for the fix!
