### ISSUE TITLE
Cannot resolve module 'package.version'

### ISSUE THREAD

**Issue by yale** [algolia/algoliasearch-client-js#77]
Hi folks. After getting this set up in a new project, I'm seeing this error:

```
Module not found: Error: Cannot resolve module 'package.version'
```

happening here: https://github.com/algolia/algoliasearch-client-js/blob/master/src/create-algoliasearch.js#L13

If I go in and change it to just 3, all is well.

**Comment by vvo** [comment]
Hi, thanks for the report. How are you including/using the library? are you using one of the builds of jsdelivr? or are you using npm / bower?

**Comment by vvo** [comment]
Also, maybe you are trying to use our js client in Node.JS?

**Comment by yale** [comment]
I installed using `npm install --save`, using it on a react project based on this boilerplate: https://github.com/wbkd/react-starterkit. I'm including the plugin using `import 'algoliasearch'`

**Comment by vvo** [comment]
ok Ill have a look.

I think the problem lies in the fact that package.version is a string that will be interpreted by browserify. its a browserify transform (packageify). do you think your module loader can handle browserify transforms? otherwise I will find a fix.

right now we are browserify and webpack compatible.

**Comment by vvo** [comment]
@yale So I looked at browserify and webpack. It seems that webpack is not a drop-in replacement for browserify.

Our library is currently fully browserify compatible. But webpack has to make changes like handling browserify transforms automatically etc.. They will get here I am sure.

In the meantime, an easy workaround for webpack users is to:

```js
var algoliasearch = require('algoliasearch/dist/algoliasearch.js');
```

So you use the builded version. Let me know how it goes @yale 

PS: I will update the documentation for webpack users, both readme and website. Thanks.

**Comment by vvo** [comment]
Hi @yale, I made our api client webpack compatible, you can now use:

```sh
npm install algoliasearch@3.0.6 --save
```

```js
var algoliasearch = require('algoliasearch')
```

Let me know.

**Comment by yale** [comment]
hurrah, it works! thank you so much @vvo :)

**Comment by vvo** [comment]
woohoo! Happy coding.
![lrw1](https://cloud.githubusercontent.com/assets/123822/6983964/2829a5f6-da24-11e4-9043-0144aa5d9604.gif)
