### ISSUE TITLE
Clone the cached hits?

### ISSUE THREAD

**Issue by kokliKo** [algolia/algoliasearch-client-js#79]
Hey,

When we modify the content object to display it, we sometimes have a problem when content is sent from the cache, because it has already been modified before.
Would it be possible to deepclone this cached object before sending it?

Thanks!

**Comment by vvo** [comment]
YES it is.

**Comment by vvo** [comment]
Solution: store the JavaScript string in the cache content. do a JSON.parse each time we need to send a response to the user (cached or not).
