### ISSUE TITLE
ReferenceError - 'crypto' module is used but not imported

### ISSUE THREAD

**Issue by hdeflaugergues** [algolia/algoliasearch-client-js#84]
In file *src/server/builds/node.js* the method **generateSecuredApiKey()** uses the **crypto** module without importing it.
The method throws a **ReferenceError**

Add the line:
```javascript
var crypto = require('crypto');
```

**Comment by vvo** [comment]
ah good catch, sorry abt that.

@bobylito can you do the change and release a patch version?

**Comment by bobylito** [comment]
on it!

**Comment by bobylito** [comment]
The package is pushed on NPM!
