### ISSUE TITLE
Remove console.log calls

### ISSUE THREAD

**Issue by renancouto** [algolia/algoliasearch-client-js#86]
Hi, how can I remove all console.log calls on the browser version (I'm using v3)? I couldn't find anything about this on the docs.
Thanks!

**Comment by vvo** [comment]
Hi @renancouto can you show me some of the console log calls you are seeing? Thanks

**Comment by renancouto** [comment]
Hello @vvo! Yes, the logs looks like these:

On init:
```
algoliasearch init done { settings... }
```

On searches:
```
algoliasearch:/1/indexes/*/queries request start +1m
algoliasearch:/1/indexes/*/queries received response: { body... }
```

Don't get me wrong, these logs are nice, but I'd like to removed them in production. Is that possible?
