### ISSUE TITLE
server/builds/node.js: malformed end response crashes app

### ISSUE THREAD

**Issue by odeke-em** [algolia/algoliasearch-client-js#89]
Thank you for this cool search service/client!
 
My app's integration tests have been crashing quite a bit whenever deletion of a non-existant index occured. The crash happened because src/server/builds/node.js expects data as parseable JSON
which you can see from:
```javascript 
        // algoliasearch-client-js/src/server/builds/node.js#L135-140
        resolve({
          statusCode: res.statusCode,
          body: JSON.parse(Buffer.concat(chunks))
        });
```

but it actually received back response
```html
<html>
<head><title>400 Bad Request</title></head>
<body bgcolor="white">
<center><h1>400 Bad Request</h1></center>
<hr><center>nginx</center>
</body>
</html>
```

**Comment by odeke-em** [comment]
If you are interested in the client side fix, I have submitted a PR https://github.com/algolia/algoliasearch-client-js/pull/90 to address this.

**Comment by vvo** [comment]
@odeke-em I do agree we should fail-safe bad JSON responses from our own servers and I will fix this behavior.

But I could not reproduce the 400 bad request issue, here's what I tried:

```js
var client = algoliasearch('Good APPID', 'Good Admin Key');
client.deleteIndex('dsadsadkjasfdsfdsfsdfdsfsdfdsfsdfdkdjsa', function(err) {
  console.log(err);
});
```

And I do not receive any 400 bad request, could you double check?

**Comment by odeke-em** [comment]
Hello @vvo, I see that can't reproduce it. Probably it is a mix of issues + maybe rate exhaustion but I certainly caught the errored response and found it was the one tripping things out.

**Comment by odeke-em** [comment]
I can reproduce this using my app btw, just did right now. Sent you some screenshots via email.

**Comment by vvo** [comment]
Great, as a quick fix, can you `npm install algolia/algoliasearch-client-js#98c71478f872a0088fc3b5d02c87ed2876d51d6a` and let me know what happens, you should get an error about JSON parsing.

We are on the problem, cc @Nagriar

**Comment by odeke-em** [comment]
Oh yes, thanks it works great now, here is the output
```
{ 
        [AlgoliaSearchUnparsableJSONError: Could not parse the incoming response as JSON, see err.more for details]
         name: 'AlgoliaSearchUnparsableJSONError',
         message: 'Could not parse the incoming response as JSON, see err.more for details',
         more: '<html>\r\n<head><title>400 Bad Request</title></head>\r\n<body bgcolor="white">\r\n<center><h1>400 Bad Request</h1></center>\r\n<hr><center>nginx</center>\r\n</body>\r\n</html>\r\n'
}
```

**Comment by odeke-em** [comment]
Thank you @vvo for fixing this!

**Comment by DHidee66** [comment]
@vvo Is it better if the library checks the response before parsing it and not give an error at all?

**Comment by vvo** [comment]
@DHidee66 it really depends on the different cases, when the status is 500 or 404 Algolia API server is also sending us a descriptive error message in JSON.

Open a new issue with reproducible code for your react issue and we will dig into it :)
