### ISSUE TITLE
Stop committing dist/ files

### ISSUE THREAD

**Issue by vvo** [algolia/algoliasearch-client-js#92]
For all our JavaScript projects, we use http://www.jsdelivr.com/ as a great way to distribute our builds to clients.

One drawback is that we have to commit dist/ files to our github repository for them to be picked up by their bot.

As committing dist/ files can be tedious and error prone, we should be able to avoid it.

It seems that by combining https://github.com/jsdelivr/libgrabber#add-updatejson-schema and npm prepublish and gitignore we would be able to push our dist files to the npm repository only and then have jsdelivr pick them up from here.

What do you think @bobylito @pixelastic?

**Comment by bobylito** [comment]
Yep I was thinking of the same thing for the helper. :+1:

**Comment by vvo** [comment]
Will test this workflow in the places client, you can test it right now if you want otherwise Ill let you know of the outcome

**Comment by pixelastic** [comment]
Seems an interesting approach. So this will push the minified version to
npm, but not save them in the repo history, right ? Also, are the minified
version tested by the CI ?

**Comment by vvo** [comment]
> So this will push the minified version to
> npm, but not save them in the repo history, right ?

Yes and jsdelivr will take the dist from npm. This has another advantage which is jsdelivr will only pull what is on npm, rather than pull as soon as it's on master (it can be on master but not yet released).

> Also, are the minified
> version tested by the CI ?

Yes the integration tests are using the build version of algoliasearch so that we test:
- the browserify standalone generated module (export in window)
- the minification does not breaks the build

The unit tests are run with the commonJS module.

See https://github.com/algolia/algoliasearch-client-js/blob/759435012224f2db3477074e19fca43d4af3c5ca/test/run-integration.js#L20-L22 and https://github.com/algolia/algoliasearch-client-js/blob/master/zuul.config.js#L8-L13

**Comment by pixelastic** [comment]
So yeah, go for this approach and tell us how it went, this sounds good.

**Comment by vvo** [comment]
This is V4 #195
