### ISSUE TITLE
TypeError: string is not a function

### ISSUE THREAD

**Issue by OKNoah** [algolia/algoliasearch-client-js#97]
I have a strange problem where my node.js app doesn't return any search results and gives the error `[TypeError: string is not a function]`.

It is running on Heroku, and there are 3 environments (and 3 github branches). For some reason it all works fine on all but the master branch and live environment. I have merged a working branch with the master but still no luck. Running the master branch on my local machine with the same variables as the live Heroku site works fine too. Since the error does not say the line number or anything, I don't know how to investigate further. But since it just occurs when searching, I believe it's the Algolia API.

Any help appreciated.

----

Here is the code

	exports.search = function ( req, res ) {
		
		getUser( req.token )
		.then( function ( user ) {
		
			index.search( req.query.terms, function( error, result ) {
				if ( error ) { 
					console.log( error )
					return res.status( 500 ).json( error.message )
				}

				return res.status( 200 ).json( result.hits )
			}, { facetFilters: [ 'user:' + user.id, 'stream:' + req.query.stream ], page: req.query.page, hitsPerPage: req.query.show } )
		
		})
		.catch( function ( error ) {
			console.log( error )
			return res.status( 500 ).json( error.message )
		})
		
	}

**Comment by vvo** [comment]
Hello @OKNoah, it is a simple inversion of parameters, you must call search this way:

```js
index.search(query, params, function callback() {});
```

instead of:

```js

```
index.search(query, function callback() {}, params);
```js

Here's your code fixed:

```js
exports.search = function ( req, res ) {

    getUser( req.token )
    .then( function ( user ) {

        index.search( req.query.terms, { facetFilters: [ 'user:' + user.id, 'stream:' + req.query.stream ], page: req.query.page, hitsPerPage: req.query.show , , function( error, result ) {
            if ( error ) { 
                console.log( error )
                return res.status( 500 ).json( error.message )
            }

            return res.status( 200 ).json( result.hits )
        } )

    })
    .catch( function ( error ) {
        console.log( error )
        return res.status( 500 ).json( error.message )
    })

}
```

If you come from our previous nodejs client (algolia-search in npm) then have a look at our migration guide: https://github.com/algolia/algoliasearch-client-js/wiki/Node.js-v1.x.x-migration-guide

If you found a nodejs example somewhere on our website, or anywhere on the internet that is stating you should have `params` last then please let me know.

Also, since you use promises, you will be interested by the fact that our new JS client also support promises so that you can rewrite your code like this:

```js
exports.search = function ( req, res ) {

    getUser( req.token )
    .then( function ( user ) {

        return index.search( req.query.terms, { facetFilters: [ 'user:' + user.id, 'stream:' + req.query.stream ], page: req.query.page, hitsPerPage: req.query.show } )

    })
    .then(function(result) {
      return res.status( 200 ).json( result.hits )
    })
    .catch( function ( error ) {
        return res.status( 500 ).json( error.message )
    })
}
```

Nice?

Let me know if your problem is fixed.

**Comment by OKNoah** [comment]
Great,

Upgrading to version 3 did fix this problem. Still not sure why it worked on so many environment except one, maybe an old SSL bug in version 1, since we have HTTPS on our live site but not elsewhere.

Thanks a lot

**Comment by vvo** [comment]
> Still not sure why it worked on so many environment except one

I think the one environment that failed had the V3 loaded while you were using V2 style search code.

Happy we solved this, thanks!

**Comment by OKNoah** [comment]
> I think the one environment that failed had the V3 loaded while you were using V2 style search code.

Is that possible if I had `algolia-search` (old one) in the npm package dependencies list and _not_ `algoliasearch`?

**Comment by vvo** [comment]
No if you had algolia-search as a dependency then the old .search call should have worked. Strange. BUt we solved it in the end :)
