### ISSUE TITLE
Documentation mistake in batch queries

### ISSUE THREAD

**Issue by maxiloc** [algolia/algoliasearch-client-js#98]
"params:" is missing

**Comment by vvo** [comment]
you mean client.batch()? I do not think there's params prop

**Comment by vvo** [comment]
this: https://github.com/algolia/algoliasearch-client-js/tree/develop#batch-writes ? (develop branch)

**Comment by maxiloc** [comment]
Yes sorry, did the issue a bit in a hurry,

So it is in section : Multiple queries => Line 756

**Comment by vvo** [comment]
Right!
