### ISSUE TITLE
bug global.document undifined

### ISSUE THREAD

**Issue by MarioPatch** [algolia/algoliasearch-client-js#99]
Hi, I have two page. One is Okay but on the second page, I have this error :
Uncaught TypeError: Cannot read property 'location' of undefined
caused by : 
var protocol = global.document.location.protocol;
inside this lib : 
http://cdn.jsdelivr.net/algoliasearch/3/algoliasearch.js

"global" is not null
I don't understand why and I haven't found the solution. Only replace this line by : 
var protocol = window.document.location.protocol;
and all is okay but it's not a good solution...

**Comment by vvo** [comment]
Hi @MarioPatch, Can you give me a url where I can see the bug? Thanks

**Comment by vvo** [comment]
@MarioPatch I found a case where it can occurs and did a patch, this issue will be closed when we release the patch (today)

**Comment by MarioPatch** [comment]
sorry I can't give you an URL. Thank for the patch
